### ISSUE TITLE
Failed to recognise new path when changing root folder

### ISSUE THREAD

**Issue by dippynark** [lidarr/Lidarr#1012]
**Describe the bug**

When changing the root folder using 'Mass Editor' and moving the files, the Library doesn't update its file location

**To Reproduce**
1. Go to 'Library'
2. Click on 'Mass Editor'
3. Select an Artist, select a new 'Root Folder' and select 'Yes, Move the Files'
4. Browse to the artist in your Library and see the error 'Loading track files failed' where the album list should be

**Expected behavior**

Lidarr should update its file database to use the new root

**Logs**

```
[Fatal] LidarrErrorPipeline: Request Failed. GET /api/v1/trackFile

[v0.7.1.1381] NzbDrone.Common.Disk.NotParentException: /[OLD_ROOT_FOLDER]/[ARTIST]/[ALBUM]/[TRACK] is not a child of /[NEW_ROOT_FOLDER]/[ARTIST]
  at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath (System.String parentPath, System.String childPath) [0x00021] in <96b70a41daeb490db51c9994341a8d2b>:0
  at Lidarr.Api.V1.TrackFiles.TrackFileResourceMapper.ToResource (NzbDrone.Core.MediaFiles.TrackFile model, NzbDrone.Core.Music.Artist artist, NzbDrone.Core.DecisionEngine.Specifications.IUpgradableSpecification upgradableSpecification) [0x00047] in <2883fe04aa0a46f687bad43f547ee0c6>:0
  at Lidarr.Api.V1.TrackFiles.TrackFileModule+<>c__DisplayClass9_0.<GetTrackFiles>b__1 (NzbDrone.Core.MediaFiles.TrackFile f) [0x00000] in <2883fe04aa0a46f687bad43f547ee0c6>:0
  at System.Collections.Generic.List`1[T].ConvertAll[TOutput] (System.Converter`2[TInput,TOutput] converter) [0x0001a] in <254335e8c4aa42e3923a8ba0d5ce8650>:0
  at Lidarr.Api.V1.TrackFiles.TrackFileModule.GetTrackFiles () [0x00ad7] in <2883fe04aa0a46f687bad43f547ee0c6>:0
  at Lidarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00006] in <26a7215ffa4844618987ce6727897136>:0
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0
```

**System info:**
 - Lidarr Version: 0.7.1.1381
 - Operating System: CoreOS Container Linux
 - mono Version: 5.20.1.34

**Additionl info:**

I am using the Docker container [linuxserver/lidarr](https://hub.docker.com/r/linuxserver/lidarr)

**Comment by enomam** [comment]
I'll add that the same error occurs intermittently, when editing at the individual artist level.
I have to delete the entry, and then re-import the artist

**Comment by SenorSmartyPants** [comment]
I just upgraded to the LSIO nightly docker Lidarr version 0.7.1.1612 to fix this error. I'm still getting it. Should the fix have been deployed in that version, or do I need to wait.

```
lidarr           | 2020-01-27T22:09:25.593133891Z [v0.7.1.1612] NzbDrone.Common.Disk.NotParentException: /music/Blues Traveler/Four/Blues Traveler - Four - 01 - Run-Around.mp3 is not a child of /storage/media/Music/Blues Traveler
lidarr           | 2020-01-27T22:09:25.593270685Z    at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in d:\a\1\s\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 74
lidarr           | 2020-01-27T22:09:25.593313852Z    at Lidarr.Api.V1.TrackFiles.TrackFileResourceMapper.ToResource(TrackFile model, Artist artist, IUpgradableSpecification upgradableSpecification) in d:\a\1\s\src\Lidarr.Api.V1\TrackFiles\TrackFileResource.cs:line 70
lidarr           | 2020-01-27T22:09:25.593336894Z    at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
lidarr           | 2020-01-27T22:09:25.593419437Z    at Lidarr.Api.V1.TrackFiles.TrackFileModule.GetTrackFiles() in d:\a\1\s\src\Lidarr.Api.V1\TrackFiles\TrackFileModule.cs:line 97
lidarr           | 2020-01-27T22:09:25.593445396Z    at Lidarr.Http.REST.RestModule`1.<set_GetResourceAll>b__33_0(Object options) in d:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 137
lidarr           | 2020-01-27T22:09:25.593466396Z    at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
lidarr           | 2020-01-27T22:09:25.593742608Z    at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
lidarr           | 2020-01-27T22:09:25.593868319Z    at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
lidarr           | 2020-01-27T22:09:25.593892236Z    at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
lidarr           | 2020-01-27T22:09:25.593911194Z    at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
lidarr           | 2020-01-27T22:09:25.593928986Z    at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

**Comment by ta264** [comment]
The fix is has not yet been merged

**Comment by phit42** [comment]
Unfortunately I still have this issue, even in the latest version.

20-3-23 22:30:16.0|Debug|ArtistService|Updating 526 artist
20-3-23 22:30:17.5|Debug|ArtistService|526 artists updated
20-3-23 22:30:17.6|Debug|Api|[PUT] /api/v1/artist/editor: 202.Accepted (2170 ms)
...
20-3-23 22:31:44.6|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/trackFile
[v0.7.1.1381] NzbDrone.Common.Disk.NotParentException: /volume1/music/NewMusic/12 Stones/...

And since I now have way too many unmapped files, its page returns blank.

**Comment by ta264** [comment]
This was fixed in a version later than yours (that's still prerelease)

**Comment by phit42** [comment]
Sorry, I misinterpreted above info. Thanks for letting me know.
Is there a way I could manually trigger a full rescan of a root folder, so that Lidarr tries to map all music in it to existing entries?

**Comment by Jerrk** [comment]
Any ETA on this fix yet?

**Comment by ta264** [comment]
It's fixed in nightly, not ETA for that to be released as stable yet

**Comment by egyptianbman** [comment]
I am running the preview image:
```
Version
    0.7.1.1691
Package Version
    0.7.1.1691-ls4 by linuxserver.io 
```

and am getting this error.

```
app_1  | [Fatal] LidarrErrorPipeline: Request Failed. DELETE /api/v1/trackFile/4711
app_1  |
app_1  | [v0.7.1.1691] NzbDrone.Common.Disk.NotParentException: /path-to/music-old/artist/song is not a child of /path-to/music
app_1  |    at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in d:\a\1\s\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 78
app_1  |    at NzbDrone.Core.MediaFiles.MediaFileDeletionService.DeleteTrackFile(Artist artist, TrackFile trackFile) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileDeletionService.cs:line 69
app_1  |    at Lidarr.Api.V1.TrackFiles.TrackFileModule.DeleteTrackFile(Int32 id) in d:\a\1\s\src\Lidarr.Api.V1\TrackFiles\TrackFileModule.cs:line 175
app_1  |    at Lidarr.Http.REST.RestModule`1.<set_DeleteResource>b__27_0(Object options) in d:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 87
app_1  |    at Nancy.NancyModule.<>c__DisplayClass8_0`1.<Delete>b__0(Object args)                                                                                                    
app_1  |    at Nancy.NancyModule.<>c__DisplayClass10_0`1.<Delete>b__0(Object args, CancellationToken ct)
app_1  |    at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
app_1  |    at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
app_1  |    at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
app_1  |    at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```
