### ISSUE TITLE
Unable to Process Release Results from Torznab Indexer

### ISSUE THREAD

**Issue by myfrontpocket** [lidarr/Lidarr#103]
I had Jackett set up for Radarr and Sonarr, but never really used it for them, so this evening I went through the process of adding it to Lidarr since music is kind of hit or miss with Usenet.  I have RARBG and LimeTorrents set up through Jackett, and added both Torznab feeds to Lidarr. No issue there. When I search for an album, Lidarr bombs out.

17-10-16 21:11:44.0|Info|NzbSearchService|Searching 5 indexers for [A Perfect Circle - Thirteenth Step (2003)]
17-10-16 21:11:46.5|Info|DownloadDecisionMaker|Processing 32 releases
17-10-16 21:11:46.6|Error|DownloadDecisionMaker|Couldn't process release.

[v0.2.0.88] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.<GetAlbumDecisions>d__6.MoveNext() in C:\projects\lidarr\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 59

17-10-16 21:11:46.8|Error|ReleaseModule|Album search failed: Object reference not set to an instance of an object.

[v0.2.0.88] System.NullReferenceException: Object reference not set to an instance of an object.
   at Lidarr.Api.V3.Indexers.ReleaseResourceMapper.ToResource(DownloadDecision model) in C:\projects\lidarr\src\Lidarr.Api.V3\Indexers\ReleaseResource.cs:line 70
   at Lidarr.Api.V3.Indexers.ReleaseModuleBase.MapDecision(DownloadDecision decision, Int32 initialWeight) in C:\projects\lidarr\src\Lidarr.Api.V3\Indexers\ReleaseModuleBase.cs:line 25
   at Lidarr.Api.V3.Indexers.ReleaseModule.MapDecision(DownloadDecision decision, Int32 initialWeight) in C:\projects\lidarr\src\Lidarr.Api.V3\Indexers\ReleaseModule.cs:line 116
   at Lidarr.Api.V3.Indexers.ReleaseModuleBase.MapDecisions(IEnumerable`1 decisions) in C:\projects\lidarr\src\Lidarr.Api.V3\Indexers\ReleaseModuleBase.cs:line 13
   at Lidarr.Api.V3.Indexers.ReleaseModule.GetAlbumReleases(Int32 albumId) in C:\projects\lidarr\src\Lidarr.Api.V3\Indexers\ReleaseModule.cs:line 95

**Comment by Qstick** [comment]
35eeef3af62688dc388d24fb784e415e74d7387f should fix this.
