### ISSUE TITLE
Lidarr Crashing - Service unresponsive, process eats CPU like crazy

### ISSUE THREAD

**Issue by majora2007** [lidarr/Lidarr#1034]
**Describe the bug**
Lidarr Service on Windows is becoming unresponsive on a nightly basis (always happens during night). I start the service in morning, next morning it has become unresponsive. 

When unresponsive, I notice CPU utilization is at 50% and you cannot stop the service, you have to kill the executable directly. Logs do not show much other than timeouts. Trace logs added no extra info, so I'll just include normal logs. 

**To Reproduce**
1. Start lidarr on Windows
2. Wait 24 hours
3. Try to load lidarr in browser
4. Everything times out

**Expected behavior**
Not become unresponsive

**Screenshots**
N/A

**Logs**
[Day of.txt](https://github.com/lidarr/Lidarr/files/3837183/Day.of.txt)
[Night Before.txt](https://github.com/lidarr/Lidarr/files/3837184/Night.Before.txt)

**System info:**
 - Lidarr Version: 0.7.1.1574
 - Operating System Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: .Net Core
- DB Migration: 38

**Additional context**
Likely related issues:
[Issue 1](https://sentry.io/organizations/lidarr/issues/1313842456/?project=209545&query=System.Net.WebException%3A+An+error+occurred+while+sending+the+request.+The+response+ended+prematurely.&statsPeriod=14d)
[Issue 2](https://sentry.io/organizations/lidarr/issues/1305315406/?project=209545&query=System.Net.WebException%3A+An+error+occurred+while+sending+the+request.+The+response+ended+prematurely.&statsPeriod=14d)

Just occurred again, this log seems to best isolate it. 
[Lidarr.debug.txt](https://github.com/lidarr/Lidarr/files/3841282/Lidarr.debug.txt)

**Comment by majora2007** [comment]
Looking at the log and events, I see these things that stand out. Seems an Artist Scan is occurring at night and timeouts start to happen?

>> Server stops responding
>> Scanning like normal with reports of indexers and torrent client timing out

Heartbeat took longer than "00:00:01" at "11/13/2019 07:59:07 +00:00". This could be caused by thread pool starvation.

>> Scanning like normal

Couldn't download media cover for [c2c70ed6-5f10-445c-969f-2c16bc9a4c2e][Sixpence None the Richer]. An error occurred while sending the request. The response ended prematurely.

fpcalc timed out.  (multiple of these and above)

>> Scanning like normal

**Comment by majora2007** [comment]
Found error on scan:

19-11-13 10:48:59.4|Warn|FingerprintingService|AcoustId API lookup failed

[v0.7.1.1574] System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 138
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 121
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 283
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.Parser.FingerprintingService.GetResponse(HttpRequest request, Int32 retry) in d:\a\1\s\src\NzbDrone.Core\Parser\FingerprintingService.cs:line 375

**Comment by majora2007** [comment]
This issue was fixed by adding Yheti to Musicbrainz. I will run fpcalc manually on Yheti to validate, but will close this issue for now.
