### ISSUE TITLE
Renaming Failure

### ISSUE THREAD

**Issue by Joleun** [lidarr/Lidarr#1038]
It appears that there is a failure to rename files when the names are identical, but there is a change of case to a word:

Failed to rename file \\DS416PLAY\music\Patti Smith\Dream Of Life\10 - Wild Leaves.mp3: constraint failed
UNIQUE constraint failed: TrackFiles.Path

code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint faliled
UNIQUE constraint failed: TrackFiles.Path
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Marr.Data.QGen.UpdateQueryBuilder`1.Execute() in D:\a\1\s\src\Marr.Data\QGen\UpdateQueryBuilder.cs:line 156
   at Marr.Data.DataMapper.Update[T](T entity, Expression`1 filter) in D:\a\1\s\src\Marr.Data\DataMapper.cs:line 674
   at NzbDrone.Core.Datastore.BasicRepository`1.Update(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 121
   at NzbDrone.Core.MediaFiles.MediaFileService.Update(TrackFile trackFile) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileService.cs:line 66
   at NzbDrone.Core.MediaFiles.RenameTrackFileService.RenameFiles(List`1 trackFiles, Artist artist) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RenameTrackFileService.cs:line 128

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System Windsows 10 64
 - .net Framework v4.0.30319

At the moment, I'm having to run the rename twice to see if there are any failures, and then make changes manually.  It then requires changing the release, and back again, in order for Lidarr to recognize the change.  It's a bit of a messy process then so it would be great if this could be resolved.

**Comment by ta264** [comment]
I fear this is a win 10 issue - I'm not sure windows is capable of changing the case on a filename since it thinks file systems are case insensitive

**Comment by ta264** [comment]
But I suppose we might be able to detect that case and rename twice, once to a temp name, into order to make it stick

**Comment by Joleun** [comment]
You beat me to that.  I was about to respond that would it be possible by using a temp folder although that lengthens the task a little.
