### ISSUE TITLE
Blackhole download client cannot handle long paths

### ISSUE THREAD

**Issue by oldominion** [Lidarr/Lidarr#1082]
**Describe the bug**
When using blackhole, and a very long file/folder is created by the download client in the monitored directory, the Refresh Monitored Downloads task fails and won't complete successfully until the folder\file is removed\renamed. Of course, it would be great if the download client wouldn't create invalid files\folders (waiting for a fix), but equally Lidarr should be able to handle the error case by skipping the invalid file\folder instead of failing the whole job.

**To Reproduce**
1. Create an subfolder within the monitored folder of excessive length.
2. Wait for the  task to fail.

**Expected behavior**
Job should handle the invalid long file\folder names gracefully and continue. 

**Screenshots**
N/A

**Logs**
Log:
20-2-11 01:03:09.1|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Newsleecher

[v0.7.1.1381] System.IO.FileNotFoundException: File doesn't exist: D:\Public\Video\Temp\Downloading\A VERY LONG FOLDERNAME\A VERY LONG FILENAME.mkv
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileSize(String path) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 184
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at NzbDrone.Core.Download.Clients.Blackhole.ScanWatchFolder.<GetDownloadItems>d__6.MoveNext() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Blackhole\ScanWatchFolder.cs:line 74
   at NzbDrone.Core.Download.Clients.Blackhole.ScanWatchFolder.GetItems(String watchFolder, TimeSpan waitPeriod) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Blackhole\ScanWatchFolder.cs:line 41
   at NzbDrone.Core.Download.Clients.Blackhole.UsenetBlackhole.<GetItems>d__9.MoveNext() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Blackhole\UsenetBlackhole.cs:line 58
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in D:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 91

Event:
DownloadMonitoringService	Unable to retrieve queue and history items from Newsleecher: File doesn't exist: D:\Public\Video\Temp\Downloading\A VERY LONG FOLDERNAME\A VERY LONG FILENAME.mkv

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Windows
 - .net Framework (Windows) Version: 4.7.1

**Additional context**

[AB#415](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/415)

**Comment by ta264** [comment]
I'm not sure we gracefully handle long paths anywhere...

I'd suggest switching to either sabnzbd or nzbget which are both properly supported, black hole has many other issues and won't be anywhere near the top of the priority list.

**Comment by Qstick** [comment]
Closing, inactive
