### ISSUE TITLE
AcoustId API lookup failed - Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by sokratz** [lidarr/Lidarr#1084]
**Describe the bug**
AcoustId API lookup failed - Could not create SSL/TLS secure channel.

**To Reproduce**
Download new album

**Expected behavior**
no errors/fingerprint success

**Logs**

20-2-12 08:34:30.7|Info|AlbumSearchService|Completed missing search for 2 albums. 1 reports downloaded.
20-2-12 08:35:37.5|Warn|FingerprintingService|AcoustId API lookup failed

[v0.7.1.1381] System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 117
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 121
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 288
   at NzbDrone.Core.Parser.FingerprintingService.Lookup(List`1 files, Double threshold) in D:\a\1\s\src\NzbDrone.Core\Parser\FingerprintingService.cs:line 371

20-2-12 08:38:21.3|Info|RssSyncService|Starting RSS Sync

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System:  Windows
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
api cert upgraded?

**Comment by ta264** [comment]
Still an issue? Either an issue with your windows setup or the acoustid API, neither of which we control. Works for me.
