### ISSUE TITLE
Files missing in library after root folder change and manual move.

### ISSUE THREAD

**Issue by tehniemer** [lidarr/Lidarr#1107]
**Describe the bug**
Existing files disappear from the library when the root folder is changed and the files are "manually" moved to the new folder e.g. from /music/ to /data/multimedia/Music/
A re-scan does not find the files in the new root, however, going into the artist and clicking manual import brings up all the files showing the new root path but the import action does nothing. 

**To Reproduce**
1. Move files to a new folder
2. Assign the new root in lidarr
3. Use the mass editor to change the root folder and select "No, I'll move myself"
4. Re-scan
5. See error

**Expected behavior**
The files are found in the new root location and everything goes on as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/11021632/76366972-8078ca80-62f9-11ea-9f67-5a3e2af749d3.png)
![image](https://user-images.githubusercontent.com/11021632/76366973-82db2480-62f9-11ea-94f7-906b4bb18b12.png)

**Logs**
These are the logs immediately after performing a manual import of the artist.

```
[v0.7.1.1652] System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Lidarr.Api.V1.Albums.AlbumResourceMapper.ToResource(Album model) in d:\a\1\s\src\Lidarr.Api.V1\Albums\AlbumResource.cs:line 59
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Lidarr.Api.V1.Albums.AlbumResourceMapper.ToResource(IEnumerable`1 models) in d:\a\1\s\src\Lidarr.Api.V1\Albums\AlbumResource.cs:line 130
   at Lidarr.Api.V1.Albums.AlbumModuleWithSignalR.MapToResource(List`1 albums, Boolean includeArtist) in d:\a\1\s\src\Lidarr.Api.V1\Albums\AlbumModuleWithSignalR.cs:line 78
   at Lidarr.Api.V1.Albums.AlbumModule.GetAlbums() in d:\a\1\s\src\Lidarr.Api.V1\Albums\AlbumModule.cs:line 72
   at Lidarr.Http.REST.RestModule`1.<set_GetResourceAll>b__33_0(Object options) in d:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 136
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

20-3-10 17:15:21.1|Info|ImportDecisionMaker|Reading file 1/10
20-3-10 17:15:21.6|Info|ImportDecisionMaker|Reading file 2/10
20-3-10 17:15:21.9|Info|ImportDecisionMaker|Reading file 3/10
20-3-10 17:15:22.0|Info|ImportDecisionMaker|Reading file 4/10
20-3-10 17:15:22.1|Info|ImportDecisionMaker|Reading file 5/10
20-3-10 17:15:22.4|Info|ImportDecisionMaker|Reading file 6/10
20-3-10 17:15:22.7|Info|ImportDecisionMaker|Reading file 7/10
20-3-10 17:15:22.8|Info|ImportDecisionMaker|Reading file 8/10
20-3-10 17:15:23.1|Info|ImportDecisionMaker|Reading file 9/10
20-3-10 17:15:23.3|Info|ImportDecisionMaker|Reading file 10/10
20-3-10 17:15:23.5|Info|TrackGroupingService|Grouping 10 tracks
20-3-10 17:15:23.5|Info|IdentificationService|Identifying album 1/1
20-3-10 17:16:45.9|Info|ImportDecisionMaker|Reading file 1/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 2/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 3/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 4/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 5/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 6/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 7/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 8/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 9/10
20-3-10 17:16:46.0|Info|ImportDecisionMaker|Reading file 10/10
20-3-10 17:16:46.0|Info|TrackGroupingService|Grouping 10 tracks
20-3-10 17:16:46.0|Info|IdentificationService|Identifying album 1/1
20-3-10 17:17:01.1|Info|RefreshArtistService|Updating Info for 13 & God
20-3-10 17:17:02.0|Info|RefreshAlbumService|Updating Info for Men of Station
20-3-10 17:17:02.9|Info|RefreshAlbumService|Updating Info for 13 & God
20-3-10 17:17:03.5|Info|RefreshAlbumService|Updating Info for Own Your Ghost
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 1/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 2/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 3/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 4/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 5/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 6/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 7/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 8/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 9/10
20-3-10 17:17:25.1|Info|ImportDecisionMaker|Reading file 10/10
20-3-10 17:17:25.1|Info|TrackGroupingService|Grouping 10 tracks
20-3-10 17:17:25.1|Info|IdentificationService|Identifying album 1/1
```

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1652
 - Operating System : Docker 
 - Image: linuxserver/lidarr:preview

**Comment by ta264** [comment]
Dupe #1088
