### ISSUE TITLE
NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Rss feed must have a pubDate element with a valid publish date.

### ISSUE THREAD

**Issue by dfreamon** [lidarr/Lidarr#1172]
"Wanted" -> "Search All"
Doing this triggers an error for one album:

20-6-24 15:58:54.4|Error|Newznab|An error occurred while processing feed. https://api.nzb.su/api?t=search&cat=3000,3010,3020,3030,3040&extended=1&apikey=(removed)&offset=0&limit=100&q=Nina%20Simone%20Broadway%20Blues%20Ballads

[v0.7.1.1381] NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Rss feed must have a pubDate element with a valid publish date.
   at NzbDrone.Core.Indexers.RssParser.GetPublishDate(XElement item) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 196
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.GetPublishDate(XElement item) in D:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 108
   at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 157
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in D:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 70
   at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 146
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 75
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 269
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 104

This will then cause the indexers to be listed as 'not available' under "System" -> "Status"

**Expected behavior**
Should search for album without error

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Windows 10

Thank you!!

**Comment by bakerboy448** [comment]
Is this still an issue in v1?

**Comment by augustuen** [comment]
Closing due to age and lack of reply.
