### ISSUE TITLE
DivideByZeroException on Activity/Queue

### ISSUE THREAD

**Issue by dedo1911** [lidarr/Lidarr#161]
I'm facing this issue.
I still wasn't able to understand how to reproduce the error, but sometimes the queue is shown just empty.
I'm using qBittorrent as only download client.
Last time the error appeared right after Lidarr startup, after few minutes looks working just fine for a while, till this error appears again (and won't fix itself till a restart).

**Lidarr Version:** Built from 18-Dec-17 commit d08d89929aee7ea291899d1a183669f0ef16b323

**Operating System:** Windows 10

**Extracted from Logfile:**

17-12-20 11:31:55.8|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/queue

```
[v10.0.0.36128] System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at System.Decimal.op_Division(Decimal d1, Decimal d2)
   at Lidarr.Api.V1.Queue.QueueModule.<>c.<GetQueue>b__4_4(Queue q) in I:\Repos\Lidarr\src\Lidarr.Api.V1\Queue\QueueModule.cs:line 65
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SkipIterator>d__31`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Lidarr.Api.V1.Queue.QueueModule.GetQueue(PagingSpec`1 pagingSpec) in I:\Repos\Lidarr\src\Lidarr.Api.V1\Queue\QueueModule.cs:line 67
   at Lidarr.Http.LidarrRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in I:\Repos\Lidarr\src\Lidarr.Http\LidarrRestModule.cs:line 43
   at Lidarr.Api.V1.Queue.QueueModule.GetQueue(PagingResource`1 pagingResource) in I:\Repos\Lidarr\src\Lidarr.Api.V1\Queue\QueueModule.cs:line 35
   at Lidarr.Http.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in I:\Repos\Lidarr\src\Lidarr.Http\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by dedo1911** [comment]
I've found out what's the casue.
As said in the stack trace: Lidarr.Api.V1\Queue\QueueModule.cs:line 65

`ordered = ordered.ThenByDescending(q => 100 - q.Sizeleft / q.Size * 100);`

There were downloads still in "Downloading metadata" then the Size of the items in queue was 0.
I've temporarly changed that row to

`ordered = ordered.ThenByDescending(q => q.Size == 0 ? 0 : 100 - q.Sizeleft / q.Size * 100);`

Hopefully a better fix will come 👍
