### ISSUE TITLE
Error|CommandExecutor|Error occurred while executing task RescanFolders

### ISSUE THREAD

**Issue by jacekglebocki** [lidarr/Lidarr#1727]
**Describe the bug**
When I scan my library, it starts scan, goes through tracks, and then it stops scanning  because of special characters within the file name.

**To Reproduce**

**Expected behavior**
Scan is completed, renaming option, re-tagging should fix the naming later on if necessary.

**Screenshots**

**Logs**
```
20-11-3 13:24:48.0|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.8.0.1886] System.IO.FileNotFoundException: Could not find file '/share/Multimedia/Music/-- New --/Pearl Jam - Riot Act/13 - Pearl Jam - Riot Act - ï¿½ Full.flac'.
File name: '/share/Multimedia/Music/-- New --/Pearl Jam - Riot Act/13 - Pearl Jam - Riot Act - ï¿½ Full.flac'
   at System.IO.FileInfo.get_Length()
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetLocalTracks(List`1 musicFiles, DownloadClientItem downloadClientItem, ParsedTrackInfo folderInfo, FilterFilesType filter) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 108
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 145
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 153
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 281
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

**System info (please complete the following information):**
 - Lidarr Version: 0.8.0.1886
 - Operating System QNAP
 - DotNet SDK QNAP 2.1.410

**Additional context**

**Comment by jvoisin** [comment]
I can reproduce it:

```
Error occurred while executing task RescanFolders: Could not find file '/10 - G�?rard Zwang.mp3'.

System.IO.FileNotFoundException: Could not find file '/10 - G�?rard Zwang.mp3'.
File name: '10 - G�?rard Zwang.mp3'
   at System.IO.FileInfo.get_Length()
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetLocalTracks(List`1 musicFiles, DownloadClientItem downloadClientItem, ParsedAlbumInfo folderInfo, FilterFilesType filter) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 108
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 145
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 157
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 284
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 115
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

File with horribly wrong encoding in their name are making Lidarr choke.
