### ISSUE TITLE
Bug when trying to queue from Deluge or in Wanted menu 

### ISSUE THREAD

**Issue by dorel14** [lidarr/Lidarr#1963]
With latets release , i can not access to deluge queue
Message => Failed to load Queue even if it show 6 results in menu and deluge is ok when testings from settings

**To Reproduce**

1. Go to Deluged toi ensure you have something in queue
2. Click on Activity / Queue
3. => Failed to load Queue
4. Try to go in Wanted menu 
5. => Error fetching missing items

**Expected behavior**
Normaly it should show download queue or list of wanted tracks

**Platform Information (please complete the following information):**
 - OS: Debian 9
 - Docker:  No
 - Mono or .NET Version (System -> Status): Mono JIT compiler version 6.12.0.107 / NET Core Yes (3.1.10)
 - Lidarr Version: 0.8.0.2042
 - Lidarr Branch:  nightly

**Trace Logs**
21-2-5 20:18:31.2|Trace|Http|Req: 186 [GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=artist.sortName&includeUnknownArtistItems=false (from 91.*.*.169 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36)
21-2-5 20:18:31.2|Trace|LidarrErrorPipeline|Handling Exception
21-2-5 20:18:31.2|Warn|LidarrErrorPipeline|API Error

[v0.8.0.2042] Lidarr.Http.REST.BadRequestException: BadRequest: Invalid sort key artist.sortName
   at Lidarr.Http.REST.RestModule`1.ReadPagingResourceFromRequest() in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 315
   at Lidarr.Http.REST.RestModule`1.<set_GetResourcePaged>b__37_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 170
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

21-2-5 20:18:31.2|Trace|Http|Res: 186 [GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=artist.sortName&includeUnknownArtistItems=false: 400.BadRequest (15 ms)
21-2-5 20:18:31.2|Debug|Api|[GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=artist.sortName&includeUnknownArtistItems=false: 400.BadRequest (15 ms)

**Comment by ta264** [comment]
Try clearing your browser cache

**Comment by bakerboy448** [comment]
this was fixed in https://github.com/lidarr/Lidarr/commit/eb5a95cfa6044aba444614ffc71fe68ae7cba547

**Comment by dorel14** [comment]
clearing cache make it ok for queue but not for wanted

**Comment by dorel14** [comment]
After different test , the problem is only with google chrome
My version is Version 88.0.4324.150 (Build officiel) (64 bits) even after cleairng cache , cookie and so on
It's working on Firefox and Edge

**Comment by ta264** [comment]
Try chrome incognito. I'd bet you haven't managed to clear out all the stored data in chrome.

**Comment by dorel14** [comment]
Hi 
After clearing all cache and so on with ccleaner , it's now OK
