### ISSUE TITLE
TypeError: Cannot read property 'qualityWeight' of undefined

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#199]
https://sentry.io/lidarr/lidarr-ui/issues/438530510/

```
TypeError: Cannot read property 'qualityWeight' of undefined
  at Object.quality (/index.js:9909:27)
  at None (/index.js:8644:37)
  at None (/vendor.js:3899:18)
  at arrayMap (/vendor.js:821:23)
  at None (/vendor.js:3898:24)
...
(42 additional frame(s) were not displayed)
```

**Comment by AnnieTheEagle** [comment]
This appears to happen when clicking on "Manual Import", here are the contents of the download folder, perhaps the files have something missing causing this:

```
annie@aquilaos $ ls -al                                                                       
total 407656
drwxrwxrwx 1 annie annie      4096 Oct  4  2009 .
drwxr-xr-x 1 annie annie      4096 Feb 20 11:33 ..
-rwxrwxrwx 1 annie annie      1685 Aug  7  2009 Rammstein - Sehnsucht.cue
-rwxrwxrwx 1 annie annie 417414527 Aug  7  2009 Rammstein - Sehnsucht.flac
drwxrwxrwx 1 annie annie      4096 Oct  4  2009 Rammstein - Sehnsucht [Japan, POCP-7299] scans
-rwxrwxrwx 1 annie annie      3121 Aug  7  2009 Rammstein - Sehnsucht.log
```

Perhaps is caused by missing track#
