### ISSUE TITLE
Wanted list "sortName" field change

### ISSUE THREAD

**Issue by dsm1212** [lidarr/Lidarr#2020]
On 0.8 after upgrade the Wanted list won't display.

**To Reproduce**
On 0.7 go to the wanted screen and click on the artist column to sort by artist name.
Update to 0.8
Navigate to the Wanted screen. 
SEE ERROR - The list will not display just the message "Error fetching missing items"

**Expected behavior**
The list displays

**Platform Information (please complete the following information):**
 - OS: Debian Buster 
 - Docker: Yes updated from latest to develop 
 - Mono or .NET Version (System -> Status): Mono (can't find version) 
 - Browser and Version (Only needed for UI issues): 
 - Lidarr Version: 0.8.0.20420 
 - Lidarr Branch:  Moved from latest to develop 

**Trace Logs**
21-2-18 20:16:06.8|Info|RootFolderWatchingService|Watching directory /music/
21-2-18 20:17:28.6|Warn|LidarrErrorPipeline|API Error
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/6007051/Lidarr.txt)

[v0.8.0.2042] Lidarr.Http.REST.BadRequestException: BadRequest: Invalid sort key artist.sortName
   at Lidarr.Http.REST.RestModule`1.ReadPagingResourceFromRequest() in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 315
   at Lidarr.Http.REST.RestModule`1.<set_GetResourcePaged>b__37_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 170
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[Lidarr.txt](https://github.com/lidarr/Lidarr/files/6007054/Lidarr.txt)

**Comment by bakerboy448** [comment]
https://github.com/lidarr/Lidarr/issues/1963

Clear your browser cache and data

**Comment by dsm1212** [comment]
Yes that did it, thanks!
