### ISSUE TITLE
Orpheus Network suddenly cannot authenticate with gazelle

### ISSUE THREAD

**Issue by arette** [Lidarr/Lidarr#2136]
Orpheus network is my only indexer and has been working fine on (almost) latest version of lidarr until very recently where I now am getting failure to authenticate with gazelle error (see below).  To confirm the issue, I also downloaded latest windows x64 version as well and tested orpheus from vanilla install and the failure exists there too whilst I'm still able to login to orpheus network directly.

```
21-4-5 11:07:17.5|Info|DiskScanService|Completed scanning disk for Cannons
21-4-5 11:07:17.5|Info|ArtistScannedHandler|[Cannons] was recently added, performing post-add actions
21-4-5 11:07:18.5|Info|NzbSearchService|Searching 1 indexers for [Cannons - Shadows (2019)]
21-4-5 11:07:19.4|Info|MetadataService|Artist folder does not exist, skipping metadata creation
21-4-5 11:07:20.6|Error|Gazelle|An error occurred while processing feed. 

[v0.7.2.1878] System.Exception: Failed to authenticate with Gazelle.
  at NzbDrone.Core.Indexers.Gazelle.GazelleRequestGenerator.Authenticate () [0x0018c] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
  at NzbDrone.Core.Indexers.Gazelle.GazelleRequestGenerator+<GetRequest>d__19.MoveNext () [0x00021] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (System.Func`2[T,TResult] pageableRequestChainSelector, System.Boolean isRecent) [0x0019b] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 

21-4-5 11:07:21.0|Info|DownloadDecisionMaker|No results found
21-4-5 11:07:52.8|Info|NzbSearchService|Searching 0 indexers for [Cannons - Shadows (2019)]
21-4-5 11:07:52.8|Info|DownloadDecisionMaker|No results found
21-4-5 11:07:55.3|Info|NzbSearchService|Searching 0 indexers for [Cannons - Night Drive (2017)]
21-4-5 11:07:55.3|Info|DownloadDecisionMaker|No results found
21-4-5 11:08:10.1|Info|RssSyncService|Starting RSS Sync
21-4-5 11:08:10.1|Warn|FetchAndParseRssService|No available indexers. check your configuration.
21-4-5 11:08:10.1|Info|DownloadDecisionMaker|No results found
21-4-5 11:08:10.1|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
21-4-5 11:08:12.7|Warn|Gazelle|Unable to connect to indexer

[v0.7.2.1878] System.Exception: Failed to authenticate with Gazelle.
  at NzbDrone.Core.Indexers.Gazelle.GazelleRequestGenerator.Authenticate () [0x0018c] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
  at NzbDrone.Core.Indexers.Gazelle.GazelleRequestGenerator+<GetRequest>d__19.MoveNext () [0x00021] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x00045] in <798dd06330af4ca3886d7d2be5573af7>:0 
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <798dd06330af4ca3886d7d2be5573af7>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0001f] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
```

[AB#189](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/189)

**Comment by infomofo** [comment]
I am experiencing the the same issue- using the latest version- my trace is:

```
21-4-13 14:32:09.8|Warn|Gazelle|Unable to connect to indexer
[v0.8.1.2119] System.Exception: Failed to authenticate with Gazelle.
   at NzbDrone.Core.Indexers.Gazelle.GazelleRequestGenerator.Authenticate() in D:\a\1\s\src\NzbDrone.Core\Indexers\Gazelle\GazelleRequestGenerator.cs:line 129
   at NzbDrone.Core.Indexers.Gazelle.GazelleRequestGenerator.GetRequest(String searchParameters)+MoveNext() in D:\a\1\s\src\NzbDrone.Core\Indexers\Gazelle\GazelleRequestGenerator.cs:line 47
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 299```

Other details are:
```
Package Version
    0.8.1.2119-ls31 by linuxserver.io 
.NET Core
    Yes (3.1.13)
 ```

**Comment by arette** [comment]
working again (now on 0.8.1.2135)

**Comment by arette** [comment]
stopped working again

**Comment by bakerboy448** [comment]
Anyone have actual trace logs of this? So far we've only had info logs and the error itself.

but more likely to be an orpheus issue than a lidarr issue

**Comment by arette** [comment]
log trace in the original report, direct login to orpheus works. also, obviously intermittent in nature which makes it even more difficult to nail down (working again now lol)

**Comment by bakerboy448** [comment]
OP was not trace logs; those were info logs. - the word `trace` doesn't even exist in the logs.
https://wiki.servarr.com/lidarr/troubleshooting

> gazelle api

it's just the type of API system that Orpheus uses.  It's possible their site is fine, but their API is not.

**Comment by bakerboy448** [comment]
Closing given no recent reports and no trace logs of the issue; can reopen if needed

Note - pretty sure 2FA is not supported and that may be the common issue

**Comment by tubbo** [comment]
> Note - pretty sure 2FA is not supported and that may be the common issue

@bakerboy448 @arette This happened to me with Orpheus as well, and yes I'm pretty sure it has to do with 2FA because it broke as soon as I enabled that. The solution here may be to update the Gazelle API integration to use an actual API token rather than a username & password. API tokens don't require 2FA and can be revoked if necessary, so they're perfect for the use case of connecting Lidarr with a Gazelle instance like Orpheus. That said, considering it might be in use by others, it might be better to rename the integration "Gazelle Login" or something and create a new integration named "Gazelle API" which uses the actual API token auth. I think this would prevent a breaking change, and allow for those of us who use modern Gazelle instances with an API and want better security for our accounts to actually use this integration.

## the workaround

For those reading because you had this issue as well, my workaround is to use https://github.com/Jackett/Jackett to connect to Orpheus by way of my API token, then use a **Torznab** integration in Lidarr as my indexer. This works fine for now, but it would be a lot nicer if Lidarr could auth with an API token and I could just use the built-in integration.

**Comment by bakerboy448** [comment]
believe Jackett or Prowlarr should both support 2FA fine
