### ISSUE TITLE
Lidarr bundles wrong arch of fpcalc for arm64

### ISSUE THREAD

**Issue by flying-sausages** [lidarr/Lidarr#2153]
**Describe the bug**

**To Reproduce**

1. Install netcore version on `arm64` machine
2. run lidarr and see it complaining about `fpcalc` version

**Expected behavior**
Working fpcalc

**Screenshots**
see logs

**Platform Information (please complete the following information):**
 - OS: Ubuntu for ARM 20.04 
 - Docker: No
 - Mono or .NET Version (System -> Status): netcore 
 - Browser and Version (Only needed for UI issues): 
 - Lidarr Version: `0.8.0.2042`
 - Lidarr Branch: `develop`

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```
Apr 11 13:43:51 m1 Lidarr[107893]: [Error] FingerprintingService: Somthing went wrong detecting fpcalc
Apr 11 13:43:51 m1 Lidarr[107893]: [v0.8.0.2042] System.ComponentModel.Win32Exception (8): Exec format error
Apr 11 13:43:51 m1 Lidarr[107893]:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentia>
Apr 11 13:43:51 m1 Lidarr[107893]:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
Apr 11 13:43:51 m1 Lidarr[107893]:    at System.Diagnostics.Process.Start()
Apr 11 13:43:51 m1 Lidarr[107893]:    at NzbDrone.Core.Parser.FingerprintingService.GetFpcalcVersion() in D:\a\1\s\src\NzbDrone.Core\Parser\FingerprintingService.cs:line 146
Apr 11 13:43:51 m1 Lidarr[107893]:    at NzbDrone.Core.Parser.FingerprintingService..ctor(Logger logger, IHttpClient httpClient, ICacheManager cacheManager) in D:\a\1\s\src\NzbDrone.Core\Parser\FingerprintingService.cs:line 65
```

```
sausage@m1:/opt/Lidarr$ file fpcalc
fpcalc: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=bd7c1048e7a55b3e72ae937b63778da978852952, stripped
sausage@m1:/opt/Lidarr$ file Lidarr
Lidarr: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=e9dc07935d10be64346845a53d1fcea6eeff65a1, stripped
sausage@m1:/opt/Lidarr$ file $(which fpcalc)
/usr/bin/fpcalc: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=e1aa449747a50febd083a007fc490b1aadb25cad, for GNU/Linux 3.7.0, stripped
```

**Comment by Qstick** [comment]
https://github.com/lidarr/Lidarr/commit/8ad76b222be415b0d6fd2b25208a1c272659c078
