### ISSUE TITLE
Error fetching missing items following upgrade to 0.8.1.2135

### ISSUE THREAD

**Issue by BurtonPed** [lidarr/Lidarr#2180]
**Describe the bug**
The error message "Error fetching missing items" appears on the "Wanted" page in Lidarr 0.8.1.2135 following upgrade. Previous wanted items are no longer listed, although they are flagged as wanted in the individual album page. The log reports an API error when the wanted page is accessed:

21-4-21 11:26:11.5|Warn|LidarrErrorPipeline|API Error

[v0.8.1.2135] Lidarr.Http.REST.BadRequestException: BadRequest: Invalid sort key artist.sortName
   at Lidarr.Http.REST.RestModule`1.ReadPagingResourceFromRequest() in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 315
   at Lidarr.Http.REST.RestModule`1.<set_GetResourcePaged>b__37_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 170
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

**To Reproduce**
From the main menu on the left, click on the "Wanted" menu open. The wanted page (/wanted/missing) is displayed and the error message "Error fetching missing items" is displayed.

**Expected behavior**
Wanted/Missing items should display as per previous releases.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6.2.4-25556
 - Docker: Yes (Docker 18.09.0-0519 linuxserver-lidarr version 0.8.1.2135-ls47)
 - Mono or .NET Version (System -> Status): .Net Core 3.1.13
 - Browser and Version (Only needed for UI issues): Firefox 87.0 64-bit
 - Lidarr Version: 0.8.1.2135
 - Lidarr Branch: latest

Turn on Trace logs under Settings -> General and wait for the bug to occur again.

21-4-21 11:26:11.5|Warn|LidarrErrorPipeline|API Error

[v0.8.1.2135] Lidarr.Http.REST.BadRequestException: BadRequest: Invalid sort key artist.sortName
   at Lidarr.Http.REST.RestModule`1.ReadPagingResourceFromRequest() in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 315
   at Lidarr.Http.REST.RestModule`1.<set_GetResourcePaged>b__37_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 170
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

**Comment by ta264** [comment]
Clear your browser cache
