### ISSUE TITLE
BadRequest: Invalid sort key album.title

### ISSUE THREAD

**Issue by Veldkornet** [lidarr/Lidarr#2218]
**Describe the bug**
Queue fails to load due to an invalid sort key. Seems to have broken after an update (assumption).

**To Reproduce**
1. Click on Activity -> Queue

**Expected behavior**
The queue should be shown

**Screenshots**
![29B67C65-5771-4656-848D-419D0D9A99E2](https://user-images.githubusercontent.com/10297361/116123348-31d7ec80-a6c3-11eb-85f7-e01e0956514f.jpeg)

**Platform Information (please complete the following information):**
 - OS: Linux (no idea, whatever the docker container uses)
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .Net Core 3.1.13
 - Browser and Version (Only needed for UI issues): Safari on iPadOS 14.4.2
 - Lidarr Version: 0.8.1.2135
 - Lidarr Branch: 0.8.1.2135-ls48 by linuxserver.io

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```
21-4-26 19:05:47.9|Trace|Http|Req: 2280 [GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=album.title&includeUnknownArtistItems=false (from ::ffff:192.168.1.24 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15)
21-4-26 19:05:47.9|Trace|LidarrErrorPipeline|Handling Exception
21-4-26 19:05:47.9|Warn|LidarrErrorPipeline|API Error

[v0.8.1.2135] Lidarr.Http.REST.BadRequestException: BadRequest: Invalid sort key album.title
   at Lidarr.Http.REST.RestModule`1.ReadPagingResourceFromRequest() in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 315
   at Lidarr.Http.REST.RestModule`1.<set_GetResourcePaged>b__37_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 170
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/lidarr/) or  [Discord](http://lidarr.audio/discord) for support/questions.

Burn your browser cache. That should fix it, its got a old sortkey cached.
