### ISSUE TITLE
liadarr fails to download any albums

### ISSUE THREAD

**Issue by Junkbite** [lidarr/Lidarr#2272]
**Describe the bug**

all downloadsfrom jackett are failing

**To Reproduce**
search for an album manually. trying to download an album - jackett returns 409 conflict

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**

Version
0.8.1.2135
Package Version
0.8.1.2135-ls49 by linuxserver.io
.NET Core
Yes (3.1.13)
Docker
Yes

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```

21-5-26 13:00:05.5|Info|NzbSearchService|Searching 2 indexers for [50 Cent - Animal Ambition: An Untamed Desire to Win (2014)]
21-5-26 13:00:12.3|Info|DownloadDecisionMaker|Processing 6 releases
21-5-26 13:00:18.4|Warn|HttpClient|HTTP Error - Res: [GET] http://192.168.1.76:9117/dl/orpheus/?jackett_apikey=(removed)&path=Q2ZESjhIMzFFb08tNVFkRmg5NS1BNzVaMTBVMW9fUHpKT2loU0pwQmFDWU16MFJCZHNWOUM3RVhUS3Y3cERtaEd2c2VGd2x1T1Q5cGlpRXhVXzNldVRHOGd1U3dXYi1DN0tRMUNnY0pfUTVMNjRrTERTOEg3MmJIN0VxZ283RjczTGkzUUtERzJXSmdmRFlWaklIXzcweTc3eG9oS1g5QjVOQkQ2TU5kb2EyX3NUc3d0WWJvbkVYZzU5TFhqNlNOT2EtOTM3YmFjZkRkeGZodHRUdGhvLW9JMlJZ&file=50+Cent+-+Animal+Ambition+-+An+Untamed+Desire+to+Win+%5B2014%5D+%5BAlbum%5D+FLAC+%2F+Lossless+%2F+Log+(100%25)+%2F+Cue+%2F+CD+%2F+2014+Deluxe+Edition: 404.NotFound
21-5-26 13:00:18.4|Error|QBittorrent|Downloading torrent file for album '50 Cent - Animal Ambition - An Untamed Desire to Win [2014] [Album] FLAC / Lossless / Log (100%) / Cue / CD / 2014 Deluxe Edition' failed since it no longer exists (http://192.168.1.76:9117/dl/orpheus/?jackett_apikey=(removed)&path=Q2ZESjhIMzFFb08tNVFkRmg5NS1BNzVaMTBVMW9fUHpKT2loU0pwQmFDWU16MFJCZHNWOUM3RVhUS3Y3cERtaEd2c2VGd2x1T1Q5cGlpRXhVXzNldVRHOGd1U3dXYi1DN0tRMUNnY0pfUTVMNjRrTERTOEg3MmJIN0VxZ283RjczTGkzUUtERzJXSmdmRFlWaklIXzcweTc3eG9oS1g5QjVOQkQ2TU5kb2EyX3NUc3d0WWJvbkVYZzU5TFhqNlNOT2EtOTM3YmFjZkRkeGZodHRUdGhvLW9JMlJZ&file=50+Cent+-+Animal+Ambition+-+An+Untamed+Desire+to+Win+%5B2014%5D+%5BAlbum%5D+FLAC+%2F+Lossless+%2F+Log+(100%25)+%2F+Cue+%2F+CD+%2F+2014+Deluxe+Edition)

[v0.8.1.2135] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://192.168.1.76:9117/dl/orpheus/?jackett_apikey=(removed)&path=Q2ZESjhIMzFFb08tNVFkRmg5NS1BNzVaMTBVMW9fUHpKT2loU0pwQmFDWU16MFJCZHNWOUM3RVhUS3Y3cERtaEd2c2VGd2x1T1Q5cGlpRXhVXzNldVRHOGd1U3dXYi1DN0tRMUNnY0pfUTVMNjRrTERTOEg3MmJIN0VxZ283RjczTGkzUUtERzJXSmdmRFlWaklIXzcweTc3eG9oS1g5QjVOQkQ2TU5kb2EyX3NUc3d0WWJvbkVYZzU5TFhqNlNOT2EtOTM3YmFjZkRkeGZodHRUdGhvLW9JMlJZ&file=50+Cent+-+Animal+Ambition+-+An+Untamed+Desire+to+Win+%5B2014%5D+%5BAlbum%5D+FLAC+%2F+Lossless+%2F+Log+(100%25)+%2F+Cue+%2F+CD+%2F+2014+Deluxe+Edition]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 185



21-5-26 13:00:18.4|Error|ReleaseModule|Downloading torrent failed

[v0.8.1.2135] NzbDrone.Core.Exceptions.ReleaseUnavailableException: Downloading torrent failed
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://192.168.1.76:9117/dl/orpheus/?jackett_apikey=(removed)&path=Q2ZESjhIMzFFb08tNVFkRmg5NS1BNzVaMTBVMW9fUHpKT2loU0pwQmFDWU16MFJCZHNWOUM3RVhUS3Y3cERtaEd2c2VGd2x1T1Q5cGlpRXhVXzNldVRHOGd1U3dXYi1DN0tRMUNnY0pfUTVMNjRrTERTOEg3MmJIN0VxZ283RjczTGkzUUtERzJXSmdmRFlWaklIXzcweTc3eG9oS1g5QjVOQkQ2TU5kb2EyX3NUc3d0WWJvbkVYZzU5TFhqNlNOT2EtOTM3YmFjZkRkeGZodHRUdGhvLW9JMlJZ&file=50+Cent+-+Animal+Ambition+-+An+Untamed+Desire+to+Win+%5B2014%5D+%5BAlbum%5D+FLAC+%2F+Lossless+%2F+Log+(100%25)+%2F+Cue+%2F+CD+%2F+2014+Deluxe+Edition]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 185

   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 185
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 100
   at Lidarr.Api.V1.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in D:\a\1\s\src\Lidarr.Api.V1\Indexers\ReleaseModule.cs:line 124

```

**Comment by Junkbite** [comment]
http call when clicking on album to download was 

```
Request URL: http://192.168.1.76:8686/api/v1/release
Request Method: POST
Status Code: 409 Conflict
```

```
// body 
guid: "1_https://orpheus.network/torrents.php?torrentid=498442"
indexerId: 1
```

**Comment by Junkbite** [comment]
this only seems to be happening on OPS. RED works fine

**Comment by RobinDadswell** [comment]
This is specifically a jackett issue (which you've also posted on) https://github.com/Jackett/Jackett/issues/11728
