### ISSUE TITLE
[BUG]:  constraint failed NOT NULL constraint failed: TrackFiles.Quality

### ISSUE THREAD

**Issue by aram535** [Lidarr/Lidarr#2362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Scan of existing music completes, seems to identify the albums, but it goes to save the information to its database it fails with a constraint error.

### Expected Behavior

Save the scanned information into the database and present data.

### Steps To Reproduce

Started up lidarr from docker-compose (same one as sonarr, radarr, nzbget, etc)
Configured Root Folder
Configured Indexer (nzbget) 
Configured Downloader (sabnzbd) 
Library -> Update All

### Environment

```markdown
- OS: CentOS 8.4
- Lidarr: 0.8.1.2135
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 91
```

### What branch are you running?

Master

### Anything else?

end of the log file

[Info] IdentificationService: Identifying album 455/457 
[Info] IdentificationService: Identifying album 456/457 
[Info] IdentificationService: Identifying album 457/457 
[Info] ImportApprovedTracks: Importing 0 tracks 
[Error] CommandExecutor: Error occurred while executing task RescanFolders 

[v0.8.1.2135] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: TrackFiles.Quality
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1060
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 184
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 202
   at NzbDrone.Core.MediaFiles.MediaFileService.AddMany(List`1 trackFiles) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileService.cs:line 63
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 185
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 285
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 86
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

Lidarr is still running but nothing is saved and no music is presented on the library.

[AB#1444](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1444)

**Comment by bakerboy448** [comment]
Info logs are effectively useless for debugging.

> Trace Logs (https://wiki.servarr.com/lidarr/troubleshooting#logging-and-log-files)

- from the template
