### ISSUE TITLE
[BUG]: Error occurred while executing task ImportListSync: Search for 'lidarr:{removed}' failed. Invalid response received from LidarrAPI.

### ISSUE THREAD

**Issue by solarplex** [Lidarr/Lidarr#2365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Import List Sync from Spotify attempts to process items and seems to fail. When testing it starts to state "1/61" proceeds to 3/61 and then fails with the attached error from the Events Page.

### Expected Behavior

Import List Sync should either continue processing items or skip over failed ones I would assume.

### Steps To Reproduce

Add a playlist from Spotify.
Save. 
Go back to home screen and watch it fail.

### Environment

```markdown
- OS: Windows 10 Enterprise LTSC 1809
- Lidarr:0.8.1.2135 - Apr 18 2021
- Docker Install: No
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Master

### Anything else?

```
21-8-17 20:42:42.9|Info|ImportListSyncService|Starting Import List Refresh for List SpotifyPlaylist-Workout
21-8-17 20:42:46.9|Info|ImportListSyncService|Processing 61 list items
21-8-17 20:42:51.2|Warn|SkyHookProxy|Artist with ID 0 does not exist

[v0.8.1.2135] NzbDrone.Core.Datastore.ModelNotFoundException: Artist with ID 0 does not exist
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(Int32 id) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 107
   at NzbDrone.Core.Music.ArtistService.GetArtist(Int32 artistId) in D:\a\1\s\src\NzbDrone.Core\Music\Services\ArtistService.cs:line 200
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewAlbum(String title, String artist) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 276


21-8-17 20:42:51.2|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.8.1.2135] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'lidarr:438d86bf-b03b-4d9a-8022-3d4807926926' failed. Invalid response received from LidarrAPI.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewAlbum(String title, String artist) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 306
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapAlbumReport(ImportListItemInfo report) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 139
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncList(ImportListDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 77
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 293
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42


```

[AB#1463](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1463)

**Comment by bakerboy448** [comment]
We were having some server hiccups this evening; any chance it resolved it self?

also events are not logs and just the error spew really isn't helpful.  gonna need trace logs of the sync here

**Comment by solarplex** [comment]
@bakerboy448 It resolved itself! i'll be sure to do trace logs next time if I encounter something!

**Comment by amberflag48** [comment]
I've just installed and configured Lidarr today and I have the exact same issue with Spotify playlists.

Anything I can/should do? 

I am running the latest stable version in Docker.

**Comment by bakerboy448** [comment]
> I've just installed and configured Lidarr today and I have the exact same issue with Spotify playlists.
> 
> 
> 
> Anything I can/should do? 
> 
> 
> 
> I am running the latest stable version in Docker.

Please create a new GitHub issue and fill out the report completely rather than jumping on closed, resolved issues
