### ISSUE TITLE
[BUG]: Changing root folder causes all files to become unmapped

### ISSUE THREAD

**Issue by tehniemer** [Lidarr/Lidarr#2394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've remapped my docker volumes to take advantage of atomic moves and changed my root folders accordingly. After doing so all the files disappeared from my library and ended up unmapped and I've been unsuccessful in re-mapping or importing them.

### Expected Behavior

File locations are updated and files stay in library with the new path

### Steps To Reproduce

1. Map a second volume in the container that can reach the same files as the current mapped root volume in lidarr
2. Set a second root folder in lidarr that that uses the newly mapped path to the existing files
3. Use the mass editor to change the root folder of all albums to the new root folder selecting `No, I'll Move the Files Myself`
4. Delete the old root folder 
5. Re-scan the library

### Environment

```markdown
- OS: Debian 10
- Lidarr: 0.8.1.2135
- Docker Install: Yes
- Using Reverse Proxy: Yes (traefik)
- Browser: Edge
```

### What branch are you running?

Nightly

### Anything else?

Nothing additional for now.

**Comment by tehniemer** [comment]
I tried spinning up a new container to start fresh and I'm seeing the same behavior.

**Comment by tehniemer** [comment]
I've done a little more digging and I found that if I go to and artist and do a manual import, it finds all the files on the disk but is unable to determine the album, or match tracks.

This is what I'm shown when I try to manually match a track.
![image](https://user-images.githubusercontent.com/11021632/134786030-935ddd4d-deea-4e23-96c4-e69fc8e7c4f3.png)
If I click on any of those links it brings me to the correct release in musicbrainz.

**Comment by tehniemer** [comment]
I think I may have stumbled upon something in the logs. I spun up a new container, set a single folder as a root and it imported as expected. I tried again with the full direcory and I found this in the logs.

```
[Info] DiskScanService: Scanning /data/Media/Music/ 
[Error] RootFolderWatchingService: Error in Directory watcher for: {0}/data/Media/Music/ 
[v0.8.1.2135] System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
[Info] RootFolderWatchingService: Stopping directory watching for path /data/Media/Music/ 
```

**Comment by tehniemer** [comment]
Increasing `fs.inotify.max_user_watches` in `/etc/sysctl.conf` did not seem to make a difference.

**Comment by tehniemer** [comment]
Here's a [snip](https://pastebin.com/4A5quHM6) of the logs when importing starts.

**Comment by tehniemer** [comment]
Here's more errors 
```
[v0.8.1.2135] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NzbDrone.Core.MediaFiles.AudioTagService.GetTrackMetadata(TrackFile trackfile) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 78
   at NzbDrone.Core.MediaFiles.AudioTagService.WriteTags(TrackFile trackfile, Boolean newDownload, Boolean force) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 212
   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportApprovedTracks.cs:line 233
[Warn] ImportApprovedTracks: Couldn't import track /data/Media/Music/Beatles, The/Album - (1982) The Beatles/The Beatles - 01.08 - The Beatles - Happiness Is A Warm Gun.flac 
```

**Comment by Te55er4ct** [comment]
Having a very similar issue: Adding entire Root directory for library causes "failure" though can add individual folders from root directory and Lidarr will scan content and add just fine. 

`[v0.8.1.2135] System.ArgumentException: The directory name '/home/(removed)/media_array/Music/' does not exist. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at NzbDrone.Core.MediaFiles.RootFolderWatchingService.<>c__DisplayClass16_0.<StartWatchingPath>b__0() in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RootFolderWatchingService.cs:line 130


21-11-27 02:04:00.8|Warn|LidarrErrorPipeline|Invalid request Validation failed: 
 -- Name: 'Name' must not be empty.
21-11-27 02:04:13.6|Info|DiskScanService|Scanning /media/media_array/Music/
21-11-27 02:04:13.6|Error|RootFolderWatchingService|Error watching path: /media/media_array/Music/

[v0.8.1.2135] System.IO.IOException: Protocol error
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at NzbDrone.Core.MediaFiles.RootFolderWatchingService.<>c__DisplayClass16_0.<StartWatchingPath>b__0() in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RootFolderWatchingService.cs:line 146


21-11-27 02:04:13.7|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.8.1.2135] System.IO.IOException: Protocol error
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.Abstractions.DirectoryInfoWrapper.GetFiles(String searchPattern, SearchOption searchOption)
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileInfos(String path, SearchOption searchOption) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 509
   at NzbDrone.Core.MediaFiles.DiskScanService.GetAudioFiles(String path, Boolean allDirectories) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 241
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 131
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 285
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 86
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42


21-11-27 02:05:47.5|Info|RssSyncService|Starting RSS Sync
21-11-27 02:05:47.5|Warn|FetchAndParseRssService|No available indexers. check your configuration.
21-11-27 02:05:47.6|Info|DownloadDecisionMaker|No results found
21-11-27 02:05:47.6|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
21-11-27 02:15:29.3|Info|Bootstrap|Starting Lidarr - /opt/Lidarr/Lidarr.dll - Version 0.8.1.2135
21-11-27 02:15:31.8|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/lidarr]
21-11-27 02:15:32.2|Info|Router|Application mode: Interactive
21-11-27 02:15:32.7|Info|MigrationController|*** Migrating data source=/var/lib/lidarr/lidarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
21-11-27 02:15:33.4|Info|MigrationController|*** Migrating data source=/var/lib/lidarr/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
21-11-27 02:15:34.0|Info|WebHostController|Listening on the following URLs:
21-11-27 02:15:34.0|Info|WebHostController|  http://*:8686
21-11-27 02:15:34.4|Info|LidarrBootstrapper|Starting Web Server
21-11-27 02:15:36.1|Error|RootFolderWatchingService|Error watching path: /media/media_array/Music/

[v0.8.1.2135] System.ArgumentException: The directory name '/media/media_array/Music/' does not exist. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at NzbDrone.Core.MediaFiles.RootFolderWatchingService.<>c__DisplayClass16_0.<StartWatchingPath>b__0() in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RootFolderWatchingService.cs:line 130
`

**Comment by Te55er4ct** [comment]
Message:
``Error watching path: /media/media_array/Music/: The directory name '/media/media_array/Music/' does not exist. (Parameter 'path')``
Exception:
``System.ArgumentException: The directory name '/media/media_array/Music/' does not exist. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at NzbDrone.Core.MediaFiles.RootFolderWatchingService.<>c__DisplayClass16_0.<StartWatchingPath>b__0() in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RootFolderWatchingService.cs:line 130``

**Comment by Apposite245** [comment]
Any new information on this issue? Just started using Lidarr today and am facing the same problem.

**Comment by Tailslide** [comment]
Just tried setting up a new lidarr install and I'm seeing this too.

**Comment by skerit** [comment]
I'm getting this too. Same with Readarr.

**Comment by christorepl** [comment]
I also experience this issue. I've installed/ reinstalled Lidarr many times, and this used to never happen. Most files remain unmapped. Manual importing does not always work. Lidarr seems to randomly map/ unmap lots of files. It also partially deleted unmapped files that it replaced. Really odd behaviors going on!

**Comment by Tigggger** [comment]
I just set up a second lidarr at my office to act as a mirror and have run into an issue very similar to this so think they are related.

I've manually copied files to the new root folder, lidarr spots the additions and scans and adds the albums. From the library screen everything looks correct, the albums and tracks are all there, also the unmapped files screen shows that there are no unmapped files.

However if I go to an artist and select manual import, all the files appear as unmapped, once imported (again) the issue goes away.

**Comment by Coder84619** [comment]
Any update here? I'm experiencing the exact same issue. It reads through all my files/folders, but everything comes up unmapped. My first Lidarr install worked just fine. But I blew away and rebuilt my container/config and now this is happening.

**Comment by DigitalRoadi3s** [comment]
I had a docker setup that was managing all my music with Lidarr, I redeployed the container to a new host and pointed it to the same folder and everything I have is in unmapped now...

**Comment by christorepl** [comment]
I know this isn't a solution, but, this kept happening for me. I just kept using Lidarr, manually adding artists, and it would usually manage to map the files. After it sat for a few weeks? Maybe over a month? It randomly started working, and mapped all of my files.

So, if this is happening to you, and you can't find a solution, I recommend letting Lidarr sit and see if it eventually does its thing. I know it's not much help, but....that was my experience. I also had/ have a pretty large library, probably over 300k songs. Right now it's just under half a million songs.

**Comment by odedia** [comment]
This happens in TrueCharts fresh install as well. Seems like there's no resolution for several years?

**Comment by primalcurve** [comment]
I have also run into this issue. I was able to figure out a solution for my particular version of the problem.

The problematic files looked like this:
```
/path/to/Music/A/Artist Name, The/0000 - Album Title/00 - Track Title.ext
```
I had left the Lidarr naming scheme this way:
```
{Release Year} - {Album Title}/{track:00} - {Track Title}
```
When the unmapped files executor runs, it seems to try and guess the artist name based on the file structure alone. It does not seem to use tags. Since the artist name is not in the filename *or* the parent directory, it stops guessing and quits. The fix was to change the filename to something the executor can guess:
```
/path/to/Music/A/Artist Name, The/0000 - Album Title/00 - The Artist Name - Track Title.ext
```
Thus I changed my naming scheme to (I also did this with the Multi Disc Track Format):
```
{Release Year} - {Album Title}/{track:00} - {Artist CleanName} - {Track Title}
```
---
One reason I struggled to figure this out was because I also use Picard to import tracks. I have Picard both tag and rename to this:
```
/path/to/Music/A/Artist Name, The/0000 - Album Title/00 - The Artist Name - Track Title.ext
```

This worked for a majority of artists, but it caused an *additional* issue that made troubleshooting difficult. Picard's renaming script can do a single initial of the artist's sort name. So for an artist like The Cool Guys, it would sort to `C/Cool Guys, The`, but Lidarr doesn't have this feature. If the first word in an artist's name is "A" or "The", it will default to A and T respectively when creating the folders. So if I'm not paying attention, Picard will put files in one folder, and Lidarr another. Lidarr seems to be able to resolve this in the album view, but not in the unmapped files view. So be careful of that.
