### ISSUE TITLE
Lidarr fails to handle illegal naming

### ISSUE THREAD

**Issue by bobloadmire** [lidarr/Lidarr#248]
Downloading torrent with illegal naming cause Lidarr to fail to connect to the torrent client, throwing error:
Unable to communicate with qBT. Cannot combine OsPaths of different platforms ('D:\Downloads\' + 'Deadmau5 - For Lack of a Better Name [2009/MP3/V0(VBR)]')

I'm not entirely sure where lidarr is getting the " + ", it's not pat of the torrent name or folder structure in qBittorrent.

You have to delete the torrent and restart Lidarr to get it to connect to the torrent client again.

[v0.2.0.295] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://192.168.1.217:9091/command/deletePerm]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\lidarr\src\NzbDrone.Common\Http\HttpClient.cs:line 94
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\lidarr\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 225
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\lidarr\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 241
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.RemoveTorrent(String hash, Boolean removeData, QBittorrentSettings settings) in C:\projects\lidarr\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 118
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.RemoveItem(String hash, Boolean deleteData) in C:\projects\lidarr\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 167
   at Lidarr.Api.V1.Queue.QueueActionModule.Remove(Int32 id, Boolean blacklist) in C:\projects\lidarr\src\Lidarr.Api.V1\Queue\QueueActionModule.cs:line 131
   at Lidarr.Api.V1.Queue.QueueActionModule.Remove() in C:\projects\lidarr\src\Lidarr.Api.V1\Queue\QueueActionModule.cs:line 100
   at Lidarr.Api.V1.Queue.QueueActionModule.<.ctor>b6_3(Object x) in C:\projects\lidarr\src\Lidarr.Api.V1\Queue\QueueActionModule.cs:line 41
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>cDisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by bobloadmire** [comment]
also i'm not sure what part of the folder name is not valid, brackets etc are still valid on windows.

**Comment by bobloadmire** [comment]
upon further inspection it looks like the foward slashes are causing the issue.

**Comment by bobloadmire** [comment]
after deleting all offending torrents, lidarr still is throwing "All download clients are unavailable due to failures" BUT connection passes Test in the client settings
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/1826427/Lidarr.txt)

**Comment by bobloadmire** [comment]
ok, this error appears fatal, i can't restart Lidarr from the GUI. have to forcequit.

**Comment by danielunderwood** [comment]
Same as Radarr/Radarr#1761

**Comment by bobloadmire** [comment]
isee the priority was marked as low, this error complete kills Lidarr, should it not have a higher priority?

**Comment by Qstick** [comment]
That priority is on the radarr git, we have set no priority yet

**Comment by Qstick** [comment]
In regards to Lidarr still saying clients are unavailable, that will go away with time. Lidarr has an escalating backoff logic meaning for each recurring failure Lidarr will wait longer to try again.

**Comment by danielunderwood** [comment]
Sentry issue: [LIDARR-T4](https://sentry.io/lidarr/lidarr/issues/563820750/)

**Comment by Qstick** [comment]
Is this still happening in nightly?

**Comment by Levi--G** [comment]
Is there an update on this? i am having this exact issue.

**Comment by ta264** [comment]
No. This is an issue in sonarr too, the problem is the qbittorrent API doesn't tell us the sanitized name. You can work around by renaming the torrent in qbit but it won't import. If it's a issue try a different torrent client with a better API...

**Comment by Levi--G** [comment]
Santitizing the name could become part of the qbit integration... That being said, what client do you recommend as i had the most stable experience with qbit so far. no µ- or bit- plz...

**Comment by OregonGunslinger** [comment]
In my case, it's the attempt to concatenate a linux path with a filename that contains an escaped apostrophe. 

`[v0.6.2.883] System.Exception: Cannot combine OsPaths of different platforms ('/opt/downloads/Completed/' + 'Arlo Guthrie - Alice\'s Restaurant (1990) 320 vtwin88cube')
  at NzbDrone.Common.Disk.OsPath.op_Addition (NzbDrone.Common.Disk.OsPath left, NzbDrone.Common.Disk.OsPath right) [0x0002f] in <661475469d074ecf9c4fa9103b859bad>:0 
  at NzbDrone.Common.Disk.OsPath.op_Addition (NzbDrone.Common.Disk.OsPath left, System.String right) [0x00007] in <661475469d074ecf9c4fa9103b859bad>:0 
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems () [0x00170] in <5ef528d97f504a2eb51961f386df9d8b>:0 
  at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads (NzbDrone.Core.Download.IDownloadClient downloadClient) [0x0000c] in <5ef528d97f504a2eb51961f386df9d8b>:0 `
