### ISSUE TITLE
[BUG]: Album Studio pane yields 500.InternalServerError and doesn't show anything

### ISSUE THREAD

**Issue by DeathOfBalance** [Lidarr/Lidarr#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Album Studio" pane under "Library" is completely blank. It used to work as I was importing artists, but somewhere along the way it stopped working. See [this picture](https://i.imgur.com/wcmipTX.png). I tried completely reinstalling the program and the same thing happened again as more and more artists were being added.

### Expected Behavior

For the Album Studio pane to display what it's supposed to.

### Steps To Reproduce

1. Install Lidarr.
2. Add artists to the library.
3. At first, the pane shows what it's supposed to.
4. Eventually, as more and more artists get added, the pane breaks (see trace logs); I do not understand what causes the change.

### Environment

```markdown
- OS: Windows 10
- Lidarr: 0.8.1.2135
- Docker Install: No? (I'm not sure what this is.)
- Using Reverse Proxy: No? (I'm not sure what this is.)
- Browser: Brave or Firefox
```

### What branch are you running?

Master

### Anything else?

This is my trace log:

```
21-11-28 17:27:30.4|Trace|CommandQueueManager|Updating command status
21-11-28 17:27:30.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
21-11-28 17:27:30.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
21-11-28 17:27:30.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
21-11-28 17:27:30.4|Trace|EventAggregator|Publishing CommandExecutedEvent
21-11-28 17:27:30.4|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
21-11-28 17:27:30.4|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
21-11-28 17:27:30.4|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
21-11-28 17:27:30.4|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
21-11-28 17:27:30.4|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0068758]
21-11-28 17:27:30.4|Trace|Http|Req: 154 [GET] /api/v1/command (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36)
21-11-28 17:27:30.4|Trace|CommandQueueManager|Getting all commands
21-11-28 17:27:30.4|Trace|Http|Res: 154 [GET] /api/v1/command: 200.OK (0 ms)
21-11-28 17:27:30.4|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
21-11-28 17:27:37.3|Trace|Scheduler|Pending Tasks: 0
21-11-28 17:27:40.7|Trace|Http|Req: 155 [GET] /api/v1/album (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36)
21-11-28 17:27:40.9|Trace|LidarrErrorPipeline|Handling Exception
21-11-28 17:27:40.9|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/album

[v0.8.1.2135] System.Collections.Generic.KeyNotFoundException: The given key '111' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Lidarr.Api.V1.Albums.AlbumModule.GetAlbums() in D:\a\1\s\src\Lidarr.Api.V1\Albums\AlbumModule.cs:line 80
   at Lidarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


21-11-28 17:27:40.9|Trace|Http|Res: 155 [GET] /api/v1/album: 500.InternalServerError (217 ms)
21-11-28 17:27:40.9|Debug|Api|[GET] /api/v1/album: 500.InternalServerError (217 ms)

```

[AB#2005](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2005)

**Comment by dorel14** [comment]
Hello i have the same problem 
Version : 1.1.0.2649

Can someone have a look at this bug ?

**Comment by ramair02** [comment]
I am having the same issue. Blank Album Studio pane. It never loads.

**Comment by Tailslide** [comment]
Same:

```
{
  "message": "The given key \u0027841\u0027 was not present in the dictionary.",
  "description": "System.Collections.Generic.KeyNotFoundException: The given key \u0027841\u0027 was not present in the dictionary.\n   at Lidarr.Api.V1.Albums.AlbumController.GetAlbums(Nullable\u00601 artistId, List\u00601 albumIds, String foreignAlbumId, Boolean includeAllArtistAlbums) in D:\\a\\1\\s\\src\\Lidarr.Api.V1\\Albums\\AlbumController.cs:line 68\n   at lambda_method526(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Lidarr.Http\\Middleware\\BufferingMiddleware.cs:line 28\n   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Lidarr.Http\\Middleware\\IfModifiedMiddleware.cs:line 41\n   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Lidarr.Http\\Middleware\\CacheHeaderMiddleware.cs:line 33\n   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Lidarr.Http\\Middleware\\UrlBaseMiddleware.cs:line 27\n   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Lidarr.Http\\Middleware\\VersionMiddleware.cs:line 28\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}
```

**Comment by bakerboy448** [comment]
Works fine / can't reproduce in 1.2.1.3195
