### ISSUE TITLE
Import list headphones not working

### ISSUE THREAD

**Issue by dorel14** [Lidarr/Lidarr#2642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've tested importing list from my headphones and i only obtain an error with these logs 
~~~

~~~

I'have tested reading the json generated in another json parser and everything is ok 

### Expected Behavior

I expect it will import my list from heaphones

### Steps To Reproduce

Go to list  and try to add headphones

### Environment

```
Debian 9
Lidarr version 0.8.1.2135

reverse proxy : nginx
Browser : Google Chrome
```

### What branch are you running?

Develop

### Trace Logs?

22-2-12 18:49:18.9|Warn|HeadphonesImport|Unable to connect to import list

[v0.8.1.2135] Newtonsoft.Json.JsonReaderException: Error parsing Infinity value. Path '', line 1, position 2.
   at Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(ReadType readType, Boolean matched)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Core.ImportLists.HeadphonesImport.HeadphonesImportParser.ParseResponse(ImportListResponse importListResponse) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HeadphonesImport\HeadphonesImportParser.cs:line 28
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 184
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 212

22-2-12 18:49:18.9|Warn|LidarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to import list, check the log for more details
22-2-12 18:49:25.9|Warn|HeadphonesImport|Unable to connect to import list

[v0.8.1.2135] Newtonsoft.Json.JsonReaderException: Error parsing Infinity value. Path '', line 1, position 2.
   at Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(ReadType readType, Boolean matched)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Core.ImportLists.HeadphonesImport.HeadphonesImportParser.ParseResponse(ImportListResponse importListResponse) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HeadphonesImport\HeadphonesImportParser.cs:line 28
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 184
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 212

22-2-12 18:49:25.9|Warn|LidarrErrorPipeline|Invalid request Validation failed: 

[AB#2573](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2573)

**Comment by bakerboy448** [comment]
Just the error message and validation saying the list failed are not the trace logs that are REQUIRED for bug reports.

See the wiki link within the bug template and please provide the proper logs that are required - ideally not directly in the Issue itself as they are very difficult to read.

**Comment by dorel14** [comment]
Hi 
Debug logs are here
[https://pastebin.com/WWUZj2u6](url)

Trace logs are here 
[https://pastebin.com/CWSztGuV](url)

**Comment by Qstick** [comment]
Can you provide the output of `http://localhost:8181/headphones/api?cmd=getIndex&apikey=(removed)` (use your api key)
