### ISSUE TITLE
JsonException in Settings -> Connect and when sending notifications

### ISSUE THREAD

**Issue by Daniel15** [Lidarr/Lidarr#2733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Settings -> Connect shows "Unable to load Notifications", and the following error is logged:

```
[Fatal] LidarrErrorPipeline: Request Failed. GET /api/v1/notification
[v0.8.1.2135] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.to | LineNumber: 7 | BytePositionInLine: 9.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 64
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.All() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 39
   at Lidarr.Api.V1.ProviderModuleBase`3.GetAll() in D:\a\1\s\src\Lidarr.Api.V1\ProviderModuleBase.cs:line 56
   at Lidarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

### Expected Behavior

The page should load properly

### Steps To Reproduce

Go to `/settings/connect`

### Environment

```markdown
- OS: Debian Linux 11 (Bullseye)
- Lidarr: v0.8.1.2135
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 98.02
```

### What branch are you running?

Master

### Trace Logs?

```
22-4-2 18:12:45.0|Trace|Http|Req: 42 [GET] /api/v1/notification (from ::ffff:172.21.0.7 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0)
22-4-2 18:12:45.1|Trace|LidarrErrorPipeline|Handling Exception
22-4-2 18:12:45.1|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/notification

[v0.8.1.2135] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.to | LineNumber: 7 | BytePositionInLine: 9.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 64
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.All() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 39
   at Lidarr.Api.V1.ProviderModuleBase`3.GetAll() in D:\a\1\s\src\Lidarr.Api.V1\ProviderModuleBase.cs:line 56
   at Lidarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 152
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


22-4-2 18:12:45.1|Trace|Http|Res: 42 [GET] /api/v1/notification: 500.InternalServerError (63 ms)
22-4-2 18:12:45.1|Debug|Api|[GET] /api/v1/notification: 500.InternalServerError (63 ms)
```

**Comment by bakerboy448** [comment]
Just the error spew are not trace logs.

How can the bug template be improved to clarify that? The wiki link explains everything.

> Trace Logs (https://wiki.servarr.com/lidarr/troubleshooting#logging-and-log-files) 
> ***Generally speaking, all bug reports must have trace logs provided.***

**Comment by Daniel15** [comment]
@bakerboy448 Sorry! I was only looking at the Docker logs and forgot that trace logs go to a separate file!

This is literally all that's in the trace log for this issue:
```
22-4-2 18:12:45.0|Trace|Http|Req: 42 [GET] /api/v1/notification (from ::ffff:172.21.0.7 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0)
22-4-2 18:12:45.1|Trace|LidarrErrorPipeline|Handling Exception
22-4-2 18:12:45.1|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/notification

[v0.8.1.2135] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.to | LineNumber: 7 | BytePositionInLine: 9.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 64
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.All() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 39
   at Lidarr.Api.V1.ProviderModuleBase`3.GetAll() in D:\a\1\s\src\Lidarr.Api.V1\ProviderModuleBase.cs:line 56
   at Lidarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Lidarr.Http\REST\RestModule.cs:line 152
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


22-4-2 18:12:45.1|Trace|Http|Res: 42 [GET] /api/v1/notification: 500.InternalServerError (63 ms)
22-4-2 18:12:45.1|Debug|Api|[GET] /api/v1/notification: 500.InternalServerError (63 ms)
```

**Comment by Daniel15** [comment]
I just realised this issue also happens whenever Lidarr tries to send a notification (which is always failing for me now) - Updated the title to reflect that.

**Comment by Daniel15** [comment]
Since it wasn't working anyways, I shut down Lidarr and completely blew away all notification configurations (after getting a copy of the raw data in the DB)
```
$ cp lidarr.db lidarr.db.bak20220402
$ sqlite3 lidarr.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> select * from notifications;
1|Plex|0|{
  "host": ".....
...........

sqlite> delete from Notifications;
```

Then started Lidarr again, went to the Connect page (which was working again of course), and readded all the connections I had. It's working fine now. 🤔

Guess I can close this out, even if I never did actually find the root cause.
