### ISSUE TITLE
Couldn't find valid ICU package after upgrade to icu 71.1

### ISSUE THREAD

**Issue by ashleybone** [Lidarr/Lidarr#2770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Arch Linux, the upgrade to icu 71.1 (from 70.1) results in the following error when starting Lidarr:

```
> /usr/lib/lidarr/bin/Lidarr -nobrowser

Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at NzbDrone.Common.EnvironmentInfo.StartupContext..ctor(System.String[])
   at NzbDrone.Console.ConsoleApp.Main(System.String[])
```
Lidarr starts normally if I set the environmental variable  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT to 1.

### Expected Behavior

Lidarr starts normally.

### Steps To Reproduce

1. Install Lidarr via AUR package 'lidarr'.
2. Update Arch system to upgrade icu to 71.1
3. Run Lidarr.

### Environment

```markdown
- OS: Arch Linux
- Lidarr: Lidarr 0.8.1.2135
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 99
```

### What branch are you running?

Master

### Trace Logs?

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant │community/wikicurses 1.4-6
to true if you want to run with no globalization support.                                                                                │    A simple curses interface for accessing Wikipedia
   at System.Environment.FailFast(System.String)                                                                                         │ashley@regulus-$ 
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()                                                             │
   at System.Globalization.GlobalizationMode..cctor()                                                                                    │
   at System.Globalization.CultureData.CreateCultureWithInvariantData()                                                                  │
   at System.Globalization.CultureData.get_Invariant()                                                                                   │
   at System.Globalization.CultureInfo..cctor()                                                                                          │
   at System.Globalization.CultureInfo.get_CurrentCulture()                                                                              │
   at NzbDrone.Common.EnvironmentInfo.StartupContext..ctor(System.String[])                                                              │
   at NzbDrone.Console.ConsoleApp.Main(System.String[])                                                                                  │
```

[AB#3016](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3016)

**Comment by bakerboy448** [comment]
appears to be a non-issue with nightly

> Someone just said on discord

> > You can work around this issue for now by setting the environment
> > variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT to 1 when you run
> > lidarr.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/lidarr/) or  [Discord](http://lidarr.audio/discord) for support/questions.

**Comment by ta264** [comment]
Don't use `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`, it breaks regex.

You can't use use icu77. Downgrade to a supported version I think.
