### ISSUE TITLE
Updating to 1.0.1.2578 " Error occurred while executing task ApplicationUpdate: Permission denied" 

### ISSUE THREAD

**Issue by MarkFace91** [Lidarr/Lidarr#2811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,,

I'm a  code noob in need of some help.
Currently i'm unable to update to update to 1.0.1.2578, 
i'm running lidarr on my synology nas, and i did not change any permissions since the last update
a clean install didn't help either.

Please help!

### Expected Behavior

The update to be succesvol

### Environment

```markdown
- OS: DSM 7
- Lidarr:0.8.0.2042
- Docker Install: no
- Using Reverse Proxy: no
- Browser: edge
```

### What branch are you running?

Develop

### Trace Logs?

Error occurred while executing task ApplicationUpdate: Permission denied

System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 186
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 158
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 276
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 84
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
[lidarr_log.txt](https://github.com/Lidarr/Lidarr/files/8677323/lidarr_log.txt)

[AB#3134](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3134)

**Comment by ta264** [comment]
The synocommunity packages are broken on DSM 7.1

We are trialling some "official" packages here: https://github.com/Servarr/spksrc/releases/tag/v69

Try replacing your existing package with that.  You'll need to download a backup from the old lidarr, remove the package, install the new one, and then restore the backup.

**Comment by MarkFace91** [comment]
Thanks  man!  that worked  like a charm
