### ISSUE TITLE
Import via API does not log correctly in EventHistory

### ISSUE THREAD

**Issue by RandomUser345** [Lidarr/Lidarr#2856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When importing an album via API with `/api/v1/command {"name":"DownloadedAlbumsScan","path":"[path]"}` the album will get imported, but it won't show in any logs.
Consoleouput is following:
```
[Info] ImportApprovedTracks: Importing 17 tracks
[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
[error repeated for every track]
```

### Expected Behavior

Import is working and shown in logs correctly.

### Environment

```markdown
- OS: Ubuntu 20.04
- Lidarr: 1.0.2.2592
- Docker Install: 1.0.2.2592-ls88 by linuxserver.io
- Using Reverse Proxy: yes, nginx
- Browser: chrome
```

### What branch are you running?

Master

### Trace Logs?

```
[Info] ImportDecisionMaker: Reading file 1/17
[Info] ImportDecisionMaker: Reading file 2/17
[Info] ImportDecisionMaker: Reading file 3/17
[Info] ImportDecisionMaker: Reading file 4/17
[Info] ImportDecisionMaker: Reading file 5/17
[Info] ImportDecisionMaker: Reading file 6/17
[Info] ImportDecisionMaker: Reading file 7/17
[Info] ImportDecisionMaker: Reading file 8/17
[Info] ImportDecisionMaker: Reading file 9/17
[Info] ImportDecisionMaker: Reading file 10/17
[Info] ImportDecisionMaker: Reading file 11/17
[Info] ImportDecisionMaker: Reading file 12/17
[Info] ImportDecisionMaker: Reading file 13/17
[Info] ImportDecisionMaker: Reading file 14/17
[Info] ImportDecisionMaker: Reading file 15/17
[Info] ImportDecisionMaker: Reading file 16/17
[Info] ImportDecisionMaker: Reading file 17/17
[Info] TrackGroupingService: Grouping 17 tracks
[Info] IdentificationService: Identifying album 1/1
[Info] ImportApprovedTracks: Importing album 1/1
[Info] ImportApprovedTracks: Importing 17 tracks
[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Error] EventAggregator: EntityHistoryService failed while processing [TrackImportedEvent]

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.History.EntityHistoryService.Handle(TrackImportedEvent message) in D:\a\1\s\src\NzbDrone.Core\History\EntityHistoryService.cs:line 220
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


```

[AB#3326](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3326)

**Comment by meramsey** [comment]
Can confirm what looks to be almost the same error is still happening. also using lsio container
```
[Warn] ImportApprovedTracks: Couldn't import track redacted.flac 

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.AudioTagService.GetTrackMetadata(TrackFile trackfile)
   at NzbDrone.Core.MediaFiles.AudioTagService.WriteTags(TrackFile trackfile, Boolean newDownload, Boolean force) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 225
   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportApprovedTracks.cs:line 230


[Warn] ImportApprovedTracks: Couldn't import track redacted.flac 

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.AudioTagService.GetTrackMetadata(TrackFile trackfile)
   at NzbDrone.Core.MediaFiles.AudioTagService.WriteTags(TrackFile trackfile, Boolean newDownload, Boolean force) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 225
   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportApprovedTracks.cs:line 230
```
