### ISSUE TITLE
Orphius torrent issues 

### ISSUE THREAD

**Issue by ac1dburnz** [Lidarr/Lidarr#2956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When pulling music from orphus an exception error occurs”

### Expected Behavior

Torrent file is pulled 

### Environment

```markdown
- OS:  FreeBSD
- Lidarr: Lidar 1.0.2.2592
- Docker Install: no
- Using Reverse Proxy:no
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

MonoTorrent.TorrentException: Invalid torrent file specified ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader) at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader) at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s) at MonoTorrent.Torrent.Load(Stream stream, String path) --- End of inner exception stack trace --- at MonoTorrent.Torrent.Load(Stream stream, String path) at MonoTorrent.Torrent.Load(Byte[] data) at NzbDrone.Core.MediaFiles.TorrentInfo.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TorrentInfo\TorrentFileInfoReader.cs:line 14 at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 189 at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 117 at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 74 at Lidarr.Api.V1.Indexers.ReleaseController.Create(ReleaseResource release) in D:\a\1\s\src\Lidarr.Api.V1\Indexers\ReleaseController.cs:line 126 at lambda_method544(Closure , Object , Object[] ) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync() at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\BufferingMiddleware.cs:line 28 at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\IfModifiedMiddleware.cs:line 41 at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33 at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\UrlBaseMiddleware.cs:line 27 at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\VersionMiddleware.cs:line 28 at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context) at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited\|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task): Invalid torrent file specified |  
-- | --
  | 1:21pm | Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware | An unhandled exception has occurred while executing the request.: Invalid torrent file specified

[AB#3675](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3675)

**Comment by PearsonFlyer** [comment]
You are running an extremely old version of Lidarr, and you are running the old, deprecated mono version. Please update to the .net version and a newer update, and see if you continue to have this issue. It's not worth troubleshooting something that is potentially fixed.

**Comment by colinborins** [comment]
@PearsonFlyer  this is the latest avalible version for freebsd https://www.freshports.org/net-p2p/lidarr/

**Comment by ta264** [comment]
Looks like an invalid torrent. Hopefully a one off and other torrents are ok.

**Comment by colinborins** [comment]
@ta264  its not a one off. I have tried multiple torrents

**Comment by colinborins** [comment]
@PearsonFlyer  how am i using an old one? Im on 1.0.2.2592.

**Comment by colinborins** [comment]
![BE3B8E1E-00C2-4F0D-8328-5886A55930D5](https://user-images.githubusercontent.com/10972668/186770719-fb3a49c6-2c1e-4c75-b0ec-d65e24f70d40.jpeg)

**Comment by ta264** [comment]
Pearson is mistaken, that is new enough

**Comment by 2fst4u** [comment]
I get this on Orpheus too. It's apparently due to the torrent format being incompatible. Due to the nature of music torrenting and files staying up for so long, it seems to just be because they're so old and no one has trumped them.

**Comment by Qstick** [comment]
We usually see this in Prowlarr when the torrent fails due to a bad call and we get html instead, so this might not necessarily be a bad torrent.

**Comment by micah** [comment]
I've seen this as well. Other clients, such as transmission are able to handle this torrent without difficulties.

**Comment by micah** [comment]
```

2022-10-12 23:17:42.6|Fatal|LidarrErrorPipeline|Request Failed. POST /api/v1/release

[v1.0.2.2592] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.MediaFiles.TorrentInfo.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TorrentInfo\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 189
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 117
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 74
   at Lidarr.Api.V1.Indexers.ReleaseController.Create(ReleaseResource release) in D:\a\1\s\src\Lidarr.Api.V1\Indexers\ReleaseController.cs:line 126
   at lambda_method529(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by wiesel24** [comment]
Also happen to me.

**Comment by ren-del** [comment]
Hi,

I just wanted to add a few things to this bug report for what I am currently experiencing that is similar to this one before opening a new issue:

Environment:
- OS: Debian 11
- Lidarr: 1.1.4.3027
- Docker Install: Yes - 1.1.4.3027-ls119 by linuxserver.io
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.40.1

Behavior:
While trying to download a release getting invalid torrent error.

This is using the Orpheus Network Preset for the Gazelle API Indexer

Note: This only happens when FL token is not selected. It will work perfectly fine if using a FL token

Steps to Reproduce:
1. Download Client - r/ruTorrent
2. Indexer Gazelle API with Orpheus Network Preset
3. Use FL Token is **_not_** selected on Indexer
4. Attempt to download a release from any artist

Its interesting that if using FL token it works and if not it errors out and am able to query torrents from site without issue.

```
Searching indexers for [_Release Name_]. 1 active indexers
Processing 7 releases
Couldn't add report to download queue. _Release Name_]: Invalid torrent file specified
MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.MediaFiles.TorrentInfo.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TorrentInfo\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 185
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 100
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 78
Couldn't add report to download queue. _Release Name_: Invalid torrent file specified
MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.MediaFiles.TorrentInfo.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TorrentInfo\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 185
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 100
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 78
Album search completed. 0 reports downloaded.
```

**Comment by donato** [comment]
Confirmed the same exact thing as ren-del. Its broken for a torrent from 2010, but works when using a FL token.

**Comment by ren-del** [comment]
my docker crashes when trying to grab the trace logs, do you have that @donato to be able to add to this?
