### ISSUE TITLE
Error occurred while executing task ImportListSync: Search for 'lidarr:' failed. Invalid response received from LidarrAPI.

### ISSUE THREAD

**Issue by dragonlord026** [Lidarr/Lidarr#2973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to sync the Spotify playlist and it gets through a couple then I receive the error 

### Expected Behavior

It should add albums in the library

### Environment

```markdown
- OS: Windows 11
- Lidarr: 1.0.2.2592
- Docker Install: no
- Using Reverse Proxy:No
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

here is the exception part

NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'lidarr:6fd54357-1c89-4702-b1f0-324b985bc1d1' failed. Invalid response received from LidarrAPI.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewAlbum(String title, String artist) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 306
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapAlbumReport(ImportListItemInfo report) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 152
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 104
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncList(ImportListDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 77
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 294
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 115
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

[AB#3739](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3739)

**Comment by bakerboy448** [comment]
- just the error saying there is an error is not helpful nor valid for bug reports
- Trace logs are required for bug reports

**Comment by dragonlord026** [comment]
[LidarrTrace.txt](https://github.com/Lidarr/Lidarr/files/9585389/LidarrTrace.txt)


here are the trace logs sorry about that

**Comment by bakerboy448** [comment]
Searching for  `lidarr:d6d1de65-7e43-4277-b723-fc74a2b385e1` works fine now on 1.2.1.3195
