### ISSUE TITLE
AcoustId API lookup failed

### ISSUE THREAD

**Issue by Makario1337** [Lidarr/Lidarr#3009]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Current Behavior

![image](https://user-images.githubusercontent.com/74052988/192379799-637fb58f-570c-40c5-bda8-218eab8ea46a.png)

It happend before, but since two months this problem becomes more and more frequent.
Today it happened 5 times.

### Expected Behavior

Either the external API works or Lidarr would try it several times with some wait time in between.

### Steps To Reproduce

1. Run Lidarr
2. Import Releases
3. Wait for it to happen.

### Environment

```markdown
- OS: Unriad 6.10.3
- Lidarr: 1.1.0.2649
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: -
- Database: -
```

### What branch are you running?

Develop

### Trace Logs?

2022-09-26 13:20:29.4|Warn|FingerprintingService|AcoustId API lookup failed

[v1.1.0.2649] System.Net.WebException: The operation has timed out.: 'https://api.acoustid.org/v2/lookup'
 ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 122
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 122
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 261
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 267
   at NzbDrone.Core.Parser.FingerprintingService.GetResponse(HttpRequest request, Int32 retry) in D:\a\1\s\src\NzbDrone.Core\Parser\FingerprintingService.cs:line 378

[AB#3831](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3831)

**Comment by Qstick** [comment]
Closing for #3021
