### ISSUE TITLE
Preview Rename silently fails in the background for music with long file names

### ISSUE THREAD

**Issue by ericswpark** [Lidarr/Lidarr#3078]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

While Lidarr reports that renaming the music file was successful in the lefthand sidebar, it fails to properly rename the file and leaves it as-is before the rename attempt.

### Expected Behavior

Lidarr either warns the user that the filename is too long, or it says it failed to rename the file.

### Steps To Reproduce

Use the "╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ" (track 5) in "Hi This Is Flume" album as a test case.

### Environment

```markdown
- OS: UnRAID 6.11.2
- Lidarr: 1.0.2.2592
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Safari
- Database: Unsure where to check (please let me know where I can find this in a comment and I will edit the post)
```

### What branch are you running?

Master

### Trace Logs?

```
Failed to properly rollback the file move [/data/media/Music/Flume/Hi This Is Flume (2019)/05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§.flac] to [/data/media/Music/Flume/Hi This Is Flume (2019)/05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌.flac], incomplete file may be left in target path.: The path '/data/media/Music/Flume/Hi This Is Flume (2019)/05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌.flac' is too long, or a component of the specified path is too long.

System.IO.PathTooLongException: The path '/data/media/Music/Flume/Hi This Is Flume (2019)/05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌.flac' is too long, or a component of the specified path is too long.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at System.IO.Abstractions.FileWrapper.Delete(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile(String path) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 213
   at NzbDrone.Common.Disk.DiskTransferService.RollbackPartialMove(String sourcePath, String targetPath) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 421

Failed to rename file /data/media/Music/Flume/Hi This Is Flume (2019)/05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§.flac: The specified file name or path is too long, or a component of the specified path is too long.

System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.
   at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 347
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 259
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 509
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 299
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.TransferFile(TrackFile trackFile, Artist artist, List`1 tracks, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackFileMovingService.cs:line 143
   at NzbDrone.Core.MediaFiles.RenameTrackFileService.RenameFiles(List`1 trackFiles, Artist artist) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RenameTrackFileService.cs:line 124
```

**Comment by ericswpark** [comment]
May be related to #356

**Comment by ericswpark** [comment]
@bakerboy448 sorry about that. This is my first time using Lidarr and contributing to this repository. Here is a link to the Gist containing the proper trace logs: https://gist.github.com/ericswpark/9b6b75106de7e64ed85b553cfc012f6f

**Comment by GreenCobalt** [comment]
Progress on this? Having the same issue with one of my albums as well.

**Comment by bdowden** [comment]
The file in question has the original filename of `05 - â•œÎ¦Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§.flac` and is being renamed to `05 - â•œÎ¦Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œâ•«Â§â•œÏ†Â°âŒ‚â–Œ.flac`.

The issue is that, under Linux, the maximum filename length (not full path, just filename) is 255 bytes.
Using `Encoding.UTF8.GetBytes` on the original filename shows 542 bytes, but `Encoding.ASCII` shows only 244, leading me to believe the original filename is ASCII encoded.

If the filenames are both ASCII encoded, the destination filename is 329 bytes which is more than the limit of 255 bytes..

Since this is caused by an OS-level issue there's nothing that can be done code-wise to allow the rename to the current value. I think the best solution would be to check the length and if the resulting filename will be greater than the maximum bytes to keep the original filename.
