### ISSUE TITLE
Artist ABC does not import one album when scanned

### ISSUE THREAD

**Issue by splog123** [Lidarr/Lidarr#3235]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When scanning/updating artist ABCthe album Lexicon of Love (release-group/5bc5e6a3-4c24-33c3-9022-4b815d0c48d5) is not added and fails with an error. Other albums by this artist are OK.

artist/87199477-b0df-4ead-84ee-9b54b4abfc3d
release-group/5bc5e6a3-4c24-33c3-9022-4b815d0c48d5

### Expected Behavior

All albums should be added to Lidarr when this artist is scanned

### Steps To Reproduce

1. Add artist ABC (English 80s pop group)
2. When albums are added, compare to MusicBrainz, see that first album The Lexicon of Love (1982) is not added.

### Environment

```markdown
- OS: Arch
- Lidarr: 1.0.2.2592
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Firefox
- Database: SQLite
```

### What branch are you running?

Develop

### Trace Logs?

Logs from when Artist is added:

First line indicates a problem between "Lexicon of Love" and "Lexicon of Love II", both Albums are valid and they are different albums.
Contrast with "Use Your Illusion I" and "Use Your Illusion II" by Guns 'n Roses that works fine.

2022-12-20 12:23:02.0|Error|ImportDecisionMaker|Couldn't evaluate decision on [/mnt/media/Audio/music/Artists/ABC/The Lexicon of Love, /mnt/media/Audio/music/Artists/ABC/The Lexicon of Love II]

[v1.0.2.2592] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at NzbDrone.Core.MediaFiles.TrackImport.Specifications.AlbumUpgradeSpecification.IsSatisfiedBy(LocalAlbumRelease item, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\Specifications\AlbumUpgradeSpecification.cs:line 22
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.EvaluateSpec[T](IImportDecisionEngineSpecification`1 spec, T item, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 276

2022-12-20 12:23:02.0|Error|ImportDecisionMaker|Couldn't evaluate decision on [/mnt/media/Audio/music/Artists/ABC/The Lexicon of Love, /mnt/media/Audio/music/Artists/ABC/The Lexicon of Love II]

[v1.0.2.2592] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at NzbDrone.Core.MediaFiles.TrackImport.Specifications.MoreTracksSpecification.IsSatisfiedBy(LocalAlbumRelease item, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\Specifications\MoreTracksSpecification.cs:line 25
   at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.EvaluateSpec[T](IImportDecisionEngineSpecification`1 spec, T item, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\TrackImport\ImportDecisionMaker.cs:line 276

2022-12-20 12:23:04.5|Info|ImportApprovedTracks|Importing album 1/2
2022-12-20 12:23:04.5|Info|ImportApprovedTracks|Importing album 2/2
2022-12-20 12:23:04.7|Info|ImportApprovedTracks|Importing 12 tracks
2022-12-20 12:23:06.8|Info|AddArtistService|Adding Artist [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] Path: [/mnt/media/Audio/music/Artists/ABC]
2022-12-20 12:23:06.9|Info|RefreshArtistService|Updating Info for ABC
2022-12-20 12:23:07.1|Info|RefreshAlbumService|Updating Info for Up
2022-12-20 12:23:07.3|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v1.0.2.2592] System.ApplicationException: Expected query to return 1 rows but returned 0
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 121
   at NzbDrone.Core.Music.ArtistService.GetArtists(IEnumerable`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\Music\Services\ArtistService.cs:line 210
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 214
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 284
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 115
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

2022-12-20 12:23:07.4|Info|DiskScanService|Scanning /mnt/media/Audio/music/Artists/
2022-12-20 12:23:07.8|Info|MediaCoverService|Downloading Cover for [a22019f0-9dfb-3fbc-87ce-826ba9093286][Up] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/up-527caf39d0166.jpg
2022-12-20 12:23:09.1|Info|RefreshAlbumService|Updating Info for Abracadabra
2022-12-20 12:23:09.8|Info|MediaCoverService|Downloading Cover for [c2529c04-64d0-3337-b896-80e91c23af05][Abracadabra] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/abracadabra-5296233955c82.jpg
2022-12-20 12:23:11.3|Info|RefreshAlbumService|Updating Info for Traffic
2022-12-20 12:23:11.9|Info|MediaCoverService|Downloading Cover for [8b87bac0-2e7d-3346-badc-ec83283eb125][Traffic] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/traffic-527caf39cf96f.jpg
2022-12-20 12:23:14.0|Info|RefreshAlbumService|Updating Info for Alphabet City
2022-12-20 12:23:14.5|Info|MediaCoverService|Downloading Cover for [f94d3e1c-c76e-3294-b557-0cd2489a361a][Alphabet City] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/alphabet-city-51449e9708e15.jpg
2022-12-20 12:23:17.1|Info|RefreshAlbumService|Updating Info for Beauty Stab
2022-12-20 12:23:17.9|Info|MediaCoverService|Downloading Cover for [f53dea1b-c829-34f6-905e-7975e9befaf1][Beauty Stab] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/beauty-stab-5113a14d1cecd.jpg
2022-12-20 12:23:19.5|Info|RefreshAlbumService|Updating Info for The Lexicon of Love II
2022-12-20 12:23:20.2|Info|MediaCoverService|Downloading Cover for [d36f4371-a585-4ddd-a9f0-f92f97667240][The Lexicon of Love II] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/the-lexicon-of-love-ii-570e1847ebef1.jpg
2022-12-20 12:23:21.9|Info|RefreshAlbumService|Updating Info for How to Be a… Zillionaire!
2022-12-20 12:23:22.5|Info|MediaCoverService|Downloading Cover for [b2267379-9b5a-3b08-9b62-efd3ac8af3d9][How to Be a… Zillionaire!] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/how-to-be-a-zillionaire-5aa04567c39ea.jpg
2022-12-20 12:23:24.2|Info|RefreshAlbumService|Updating Info for Skyscraping
2022-12-20 12:23:24.7|Info|MediaCoverService|Downloading Cover for [3d8bcb3b-540d-3c56-bfab-08450b93fee7][Skyscraping] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/skyscraping-527caf39cb8e6.jpg
2022-12-20 12:23:26.5|Info|MediaCoverService|Downloading Fanart for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/artistbackground/abc-5068da2e9a303.JPG
2022-12-20 12:23:28.3|Info|MediaCoverService|Downloading Logo for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/hdmusiclogo/abc-555786c69db72.png
2022-12-20 12:23:29.9|Info|MediaCoverService|Downloading Poster for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/artistthumb/abc-568fe62d38480.jpg
2022-12-20 12:23:31.3|Info|MediaCoverService|Downloading Banner for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] https://imagecache.lidarr.audio/v1/tadb/artist/banner/h1g4851645608341.jpg
2022-12-20 12:23:40.5|Info|TrackGroupingService|Grouping 0 tracks
2022-12-20 12:23:40.5|Info|ImportApprovedTracks|Importing 0 tracks
2022-12-20 12:23:41.6|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v1.0.2.2592] System.ApplicationException: Expected query to return 1 rows but returned 0
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 121
   at NzbDrone.Core.Music.ArtistService.GetArtists(IEnumerable`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\Music\Services\ArtistService.cs:line 210
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 214
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 284
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 115
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

2022-12-20 12:23:41.7|Info|DiskScanService|Scanning /mnt/media/Audio/music/Artists/ABC
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 1/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 2/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 3/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 4/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 5/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 6/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 7/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 8/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 9/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 10/21
2022-12-20 12:23:43.8|Info|ImportDecisionMaker|Reading file 11/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 12/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 13/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 14/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 15/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 16/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 17/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 18/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 19/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 20/21
2022-12-20 12:23:43.9|Info|ImportDecisionMaker|Reading file 21/21
2022-12-20 12:23:43.9|Info|TrackGroupingService|Grouping 21 tracks
2022-12-20 12:23:43.9|Info|IdentificationService|Identifying album 1/2
2022-12-20 12:23:43.9|Info|IdentificationService|Identifying album 2/2
2022-12-20 12:23:44.0|Info|ImportApprovedTracks|Importing album 1/1
2022-12-20 12:23:44.0|Info|ImportApprovedTracks|Importing 11 tracks
2022-12-20 12:23:44.2|Info|DiskScanService|Completed scanning disk for ABC
2022-12-20 12:23:44.2|Info|ArtistScannedHandler|[ABC] was recently added, performing post-add actions
2022-12-20 12:23:45.0|Info|ExistingMetadataImporter|Found 9 existing metadata files
2022-12-20 12:23:45.0|Info|ExistingLyricImporter|Found 0 existing lyric files
2022-12-20 12:23:45.0|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2022-12-20 12:23:45.0|Info|ExistingExtraFileService|Found 0 extra files
2022-12-20 12:23:46.3|Info|AlbumSearchService|Performing missing search for 7 albums
2022-12-20 12:23:46.4|Info|NzbSearchService|Searching indexers for [ABC - Up (1989)]. 2 active indexers
2022-12-20 12:23:47.3|Info|DownloadDecisionMaker|Processing 2 releases
2022-12-20 12:23:47.3|Info|NzbSearchService|Searching indexers for [ABC - Abracadabra (1991)]. 2 active indexers
2022-12-20 12:23:49.5|Info|DownloadDecisionMaker|No results found
2022-12-20 12:23:49.6|Info|NzbSearchService|Searching indexers for [ABC - Traffic (2008)]. 2 active indexers
2022-12-20 12:23:51.4|Info|DownloadDecisionMaker|Processing 5 releases
2022-12-20 12:23:51.5|Info|NzbSearchService|Searching indexers for [ABC - Alphabet City (1987)]. 2 active indexers
2022-12-20 12:23:53.3|Info|DownloadDecisionMaker|Processing 17 releases
2022-12-20 12:23:53.5|Info|NzbSearchService|Searching indexers for [ABC - Beauty Stab (1983)]. 2 active indexers
2022-12-20 12:23:55.4|Info|DownloadDecisionMaker|Processing 2 releases
2022-12-20 12:23:55.4|Info|NzbSearchService|Searching indexers for [ABC - How to Be a… Zillionaire! (1985)]. 2 active indexers
2022-12-20 12:23:57.3|Info|DownloadDecisionMaker|Processing 3 releases
2022-12-20 12:23:57.5|Info|NzbSearchService|Searching indexers for [ABC - Skyscraping (1997)]. 2 active indexers
2022-12-20 12:23:59.3|Info|DownloadDecisionMaker|Processing 1 releases
2022-12-20 12:23:59.3|Info|AlbumSearchService|Completed missing search for 7 albums. 0 reports downloaded.

**Comment by bakerboy448** [comment]
Info logs are generally invalid for bug reports. As the template and header note - trace logs are required and the wiki is linked for details

**Comment by splog123** [comment]
Apologies, my bad.
I set Logging to Trace in Settings and now when deleting the Artist and adding it back, I get even less logs, see below. There are only Info logs. Is there some metadata left behind after an Artist delete that I should remove to ensure a full add is done?

This is the new trace log:

2022-12-21 11:24:16.7|Info|AddArtistService|Adding Artist [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] Path: [/mnt/media/Audio/music/Artists/ABC]
2022-12-21 11:24:16.7|Info|RefreshArtistService|Updating Info for ABC
2022-12-21 11:24:17.0|Info|RefreshAlbumService|Updating Info for Up
2022-12-21 11:24:17.7|Info|MediaCoverService|Downloading Cover for [a22019f0-9dfb-3fbc-87ce-826ba9093286][Up] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/up-527caf39d0166.jpg
2022-12-21 11:24:19.0|Info|RefreshAlbumService|Updating Info for Abracadabra
2022-12-21 11:24:19.8|Info|MediaCoverService|Downloading Cover for [c2529c04-64d0-3337-b896-80e91c23af05][Abracadabra] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/abracadabra-5296233955c82.jpg
2022-12-21 11:24:21.4|Info|RefreshAlbumService|Updating Info for Traffic
2022-12-21 11:24:22.2|Info|MediaCoverService|Downloading Cover for [8b87bac0-2e7d-3346-badc-ec83283eb125][Traffic] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/traffic-527caf39cf96f.jpg
2022-12-21 11:24:23.6|Info|RefreshAlbumService|Updating Info for Alphabet City
2022-12-21 11:24:24.7|Info|MediaCoverService|Downloading Cover for [f94d3e1c-c76e-3294-b557-0cd2489a361a][Alphabet City] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/alphabet-city-51449e9708e15.jpg
2022-12-21 11:24:26.4|Info|RefreshAlbumService|Updating Info for Beauty Stab
2022-12-21 11:24:27.0|Info|MediaCoverService|Downloading Cover for [f53dea1b-c829-34f6-905e-7975e9befaf1][Beauty Stab] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/beauty-stab-5113a14d1cecd.jpg
2022-12-21 11:24:29.2|Info|RefreshAlbumService|Updating Info for The Lexicon of Love II
2022-12-21 11:24:29.8|Info|MediaCoverService|Downloading Cover for [d36f4371-a585-4ddd-a9f0-f92f97667240][The Lexicon of Love II] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/the-lexicon-of-love-ii-570e1847ebef1.jpg
2022-12-21 11:24:31.4|Info|RefreshAlbumService|Updating Info for How to Be a… Zillionaire!
2022-12-21 11:24:32.1|Info|MediaCoverService|Downloading Cover for [b2267379-9b5a-3b08-9b62-efd3ac8af3d9][How to Be a… Zillionaire!] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/how-to-be-a-zillionaire-5aa04567c39ea.jpg
2022-12-21 11:24:33.6|Info|RefreshAlbumService|Updating Info for Skyscraping
2022-12-21 11:24:34.2|Info|MediaCoverService|Downloading Cover for [3d8bcb3b-540d-3c56-bfab-08450b93fee7][Skyscraping] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/albumcover/skyscraping-527caf39cb8e6.jpg
2022-12-21 11:24:35.7|Info|DiskScanService|Scanning /mnt/media/Audio/music/Artists/ABC
2022-12-21 11:24:36.2|Info|MediaCoverService|Downloading Fanart for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/artistbackground/abc-5068da2e9a303.JPG
2022-12-21 11:24:37.8|Info|ImportDecisionMaker|Reading file 1/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 2/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 3/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 4/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 5/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 6/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 7/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 8/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 9/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 10/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 11/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 12/21
2022-12-21 11:24:37.9|Info|MediaCoverService|Downloading Logo for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/hdmusiclogo/abc-555786c69db72.png
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 13/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 14/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 15/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 16/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 17/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 18/21
2022-12-21 11:24:37.9|Info|ImportDecisionMaker|Reading file 19/21
2022-12-21 11:24:38.0|Info|ImportDecisionMaker|Reading file 20/21
2022-12-21 11:24:38.0|Info|ImportDecisionMaker|Reading file 21/21
2022-12-21 11:24:38.0|Info|TrackGroupingService|Grouping 21 tracks
2022-12-21 11:24:38.0|Info|IdentificationService|Identifying album 1/2
2022-12-21 11:24:38.1|Info|IdentificationService|Identifying album 2/2
2022-12-21 11:24:38.1|Info|ImportApprovedTracks|Importing album 1/1
2022-12-21 11:24:38.1|Info|ImportApprovedTracks|Importing 11 tracks
2022-12-21 11:24:38.2|Info|DiskScanService|Completed scanning disk for ABC
2022-12-21 11:24:38.2|Info|ArtistScannedHandler|[ABC] was recently added, performing post-add actions
2022-12-21 11:24:38.5|Info|ExistingMetadataImporter|Found 9 existing metadata files
2022-12-21 11:24:38.5|Info|ExistingLyricImporter|Found 0 existing lyric files
2022-12-21 11:24:38.5|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2022-12-21 11:24:38.5|Info|ExistingExtraFileService|Found 0 extra files
2022-12-21 11:24:39.3|Info|MediaCoverService|Downloading Poster for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] http://assets.fanart.tv/fanart/music/87199477-b0df-4ead-84ee-9b54b4abfc3d/artistthumb/abc-568fe62d38480.jpg
2022-12-21 11:24:40.9|Info|MediaCoverService|Downloading Banner for [87199477-b0df-4ead-84ee-9b54b4abfc3d][ABC] https://imagecache.lidarr.audio/v1/tadb/artist/banner/h1g4851645608341.jpg

**Comment by augustuen** [comment]
Those are still `Info` logs. 

At this point I'll close this, seeing as it applied to Lidarrr V1. If it's still an issue with V3 we can re-open.
