### ISSUE TITLE
Unable to create, edit, or delete delay profiles

### ISSUE THREAD

**Issue by Zanaso12** [Lidarr/Lidarr#3303]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am unable to create, edit, or delete delay profiles. As the default delay profile is set to OnlyTorrent, I am unable to enable the Usenet protocol at all.

### Expected Behavior

Delay profiles should allow users to edit and delete the default delay profile, and create and edit new delay profiles as well.

### Steps To Reproduce

1. Open Lidarr web console
2. Navigate to Settings > Profiles
3. Click Edit or add a delay profile
4. Attempt to save. The specific settings do not matter

### Environment

```markdown
- OS: Unraid 
- Lidarr: 1.0.2.2592-ls107 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Vivaldi, not UI related
- Database: information not in console, github readme, or Lidarr status page except "DB Migration 59"
```

### What branch are you running?

Master

### Trace Logs?

[Fatal] LidarrErrorPipeline: Request Failed. PUT /api/v1/delayprofile/1 

[v1.0.2.2592] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: EnableUsenet
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 379
   at NzbDrone.Core.Datastore.BasicRepository`1.Update(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 221
   at NzbDrone.Core.Profiles.Delay.DelayProfileService.Update(DelayProfile profile) in D:\a\1\s\src\NzbDrone.Core\Profiles\Delay\DelayProfileService.cs:line 45
   at Lidarr.Api.V1.Profiles.Delay.DelayProfileController.Update(DelayProfileResource resource) in D:\a\1\s\src\Lidarr.Api.V1\Profiles\Delay\DelayProfileController.cs:line 60
   at lambda_method373(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[AB#4769](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4769)

**Comment by Qstick** [comment]
Looks like you switched to plugins branch and then switched back, once you go there's no coming back without a DB backup or a fresh DB

**Comment by Zanaso12** [comment]
> Looks like you switched to plugins branch and then switched back, once you go there's no coming back without a DB backup or a fresh DB

Thank you for the quick response! My only question is where would I have switched branches? I have no idea what the "plugins branch" is, so I'm not sure where or when I would have switched to it or back. Is there potentially a log I can use to determine when this occurred? I have weekly/monthly/yearly backups, so I can backup or create a new DB if needed.
