### ISSUE TITLE
Misused header name, 'Content-Encoding'

### ISSUE THREAD

**Issue by Daniel15** [Lidarr/Lidarr#3315]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm seeing this after upgrading from 1.1.1.2762 to 1.1.2.2935:
```
lidarr           | [Warn] FingerprintingService: AcoustId API lookup failed
lidarr           |
lidarr           | [v1.1.2.2935] System.InvalidOperationException: Misused header name, 'Content-Encoding'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
lidarr           |    at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
lidarr           |    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.AddRequestHeaders(HttpRequestMessage webRequest, HttpHeader headers) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 192
lidarr           |    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 96
lidarr           |    at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
lidarr           |    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
lidarr           |    at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 301
lidarr           |    at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 307
lidarr           |    at NzbDrone.Core.Parser.FingerprintingService.GetResponse(HttpRequest request, Int32 retry) in D:\a\1\s\src\NzbDrone.Core\Parser\FingerprintingService.cs:line 378
```

### Expected Behavior

AcuoustID lookup should work.

### Steps To Reproduce

Import album through Wanted &rarr; Missing &rarr; Manual Import

### Environment

```markdown
- OS: Debian Bullseye
- Lidarr: v1.1.2.2935
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox on Windows
- Database: SQLite
```

### What branch are you running?

Develop

### Trace Logs?

Exception listed above should be sufficient.

[AB#4826](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4826)

**Comment by tiswi** [comment]
I have the exact same issue

**Comment by Qstick** [comment]
Thanks for reporting
