### ISSUE TITLE
Missing items SQL query on Postgres is invalid after sorting

### ISSUE THREAD

**Issue by enticedwanderer** [Lidarr/Lidarr#3392]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Missing/wanted items list is normally shown, but I had clicked on the artist column which prompted the list to be sorted by artist. The query that's generated is not valid according to Postgres (because any sort column must also be part of the group by clause, which isn't the case here). As a result, the API fails and the list is no longer displayed.

As a side effect it is no longer possible for me to revert back to the default sort either, since the webapp memorizes the choice and always tries to go with the last entry even if it fails.

If it's relevant, I have migrated from sqlite to postgres long while back.

### Expected Behavior

Wanted/missing items should be shown and be sortable by various columns that are displayed. Alternatively, if it's not feasible to sort, or inefficient, the sort should be disabled.

Button to revert back to default sort would also help to recover from these kind of issues going forward.

### Steps To Reproduce

1. Run lidarr with a few items that are missing across at least 2 different artists.
2. Go to missing/wanted items list and try to sort by artist.

Alternatively:

Invoke the API directly with API key like so:
```
https://<lidarr_endpoint>/api/v1/wanted/missing?page=1&pageSize=20&sortDirection=descending&sortKey=artists.sortName&monitored=true
```

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- Lidarr: 1.1.4.2984
- Package Version: 1.1.4.2984-ls51 by linuxserver.io
- Docker Install: yes
- Using Reverse Proxy: Traefik
- Browser: Brave
- Database: Postgres 15.1-alpine
```

### What branch are you running?

Nightly

### Trace Logs?

```
 [Fatal] LidarrErrorPipeline: Request Failed. GET /api/v1/wanted/missing

 [v1.1.4.2984] Npgsql.PostgresException (0x80004005): 42803: column "Artists.SortName" must appear in the GROUP BY clause or be used in an aggregate function

 POSITION: 536
    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
    at Npgsql.NpgsqlDataReader.NextResult()
    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
    at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
    at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1094
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734
    at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 17
    at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 72
    at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedRecords(SqlBuilder builder, PagingSpec`1 pagingSpec, Func`2 queryFunc) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 432
    at NzbDrone.Core.Music.AlbumRepository.AlbumsWithoutFiles(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\Music\Repositories\AlbumRepository.cs:line 114
    at NzbDrone.Core.Music.AlbumService.AlbumsWithoutFiles(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\Music\Services\AlbumService.cs:line 224
    at Lidarr.Http.Extensions.RequestExtensions.ApplyToPage[TResource,TModel](PagingSpec`1 pagingSpec, Func`2 function, Converter`2 mapper) in D:\a\1\s\src\Lidarr.Http\Extensions\RequestExtensions.cs:line 135
    at Lidarr.Api.V1.Wanted.MissingController.GetMissingAlbums(Boolean includeArtist)
    at lambda_method203(Closure , Object , Object[] )
    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
 --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
 --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\BufferingMiddleware.cs:line 28
    at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
    at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
    at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
    at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\VersionMiddleware.cs:line 28
    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   Exception data:
     Severity: ERROR
     SqlState: 42803
     MessageText: column "Artists.SortName" must appear in the GROUP BY clause or be used in an aggregate function
     Position: 536
     File: parse_agg.c
     Line: 1423
     Routine: check_ungrouped_columns_walker
 Severity: ERROR;InvariantSeverity: ERROR;SqlState: 42803;MessageText: column "Artists.SortName" must appear in the GROUP BY clause or be used in an aggregate function;Position: 536;File: parse_agg.c;Line: 1423;Routine: check_ungrouped_columns_walker;SQL:
 ==== Begin Query Trace ====

 QUERY TEXT:
 SELECT "Albums".*
  FROM "Albums"
 JOIN "Artists" ON ("Albums"."ArtistMetadataId" = "Artists"."ArtistMetadataId")
 JOIN "AlbumReleases" ON ("Albums"."Id" = "AlbumReleases"."AlbumId")
 JOIN "Tracks" ON ("AlbumReleases"."Id" = "Tracks"."AlbumReleaseId")

 LEFT JOIN "TrackFiles" ON ("Tracks"."TrackFileId" = "TrackFiles"."Id")
  WHERE ("TrackFiles"."Id" IS NULL) AND ("AlbumReleases"."Monitored" = @Clause6_P1) AND ("Albums"."ReleaseDate" <= @Clause7_P1) AND (("Albums"."Monitored" = @Clause9_P1) AND ("Artists"."Monitored" = @Clause9_P2))

 GROUP BY "Albums"."Id"
   ORDER BY "SortName" DESC LIMIT 20 OFFSET 0


 PARAMETERS:
 Clause6_P1 = [true]
 Clause7_P1 = ["2023-03-07T17:22:29.6522026Z"]
 Clause9_P1 = [true]
 Clause9_P2 = [true]

 ==== End Query Trace ====
```

**Comment by enticedwanderer** [comment]
Somewhat related to #3301
