### ISSUE TITLE
Lidarr sqlite3 error in FreeBSD (Truenas): No such column: RTorrent

### ISSUE THREAD

**Issue by linit01** [Lidarr/Lidarr#3405]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After installing liar on Truenas core (Freebsd) using either "pkg" install or Truenas plugin, liar fails to startup completely with SQL logic error, no such column: RTorrent.  This error show regardless of a fresh install or upgrade to prior working app.

### Expected Behavior

Lidarr starts up completely and able to use as is or restore old data,

### Environment

```markdown
- OS: FrreeBSD lidarr 13.1-RELEASE-p7 FreeBSD 13.1-RELEASE-p7 n245418-79e75956dbb TRUENAS amd64
- Lidarr:v1.0.2.2592_1
- Docker Install: No
- Using Reverse Proxy:No
- Browser: n/a
- Database: sqlite3: 3.41.0,1
```

### What branch are you running?

Master

### Trace Logs?

[v1.0.2.2592] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: RTorrent
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NzbDrone.Core.Datastore.Migration.cdh_per_downloadclient.MoveRemoveSettings(IDbConnection conn, IDbTransaction tran) in D:\a\1\s\src\NzbDrone.Core\Datastore\Migration\051_cdh_per_downloadclient.cs:line 47
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression)
   at FluentMigrator.Expressions.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)

**Comment by linit01** [comment]
anyone?

**Comment by mvanbaak** [comment]
This is because that version of sqlite3 has disabled a feature that Lidarr depends on.
Update has been pushed already, but there are no binary packages built yet. See https://www.freshports.org/databases/sqlite3/ (The 3.41.0_1,1 version is the one with the 'fix')

For now, the easiest way to fix it is to download the sqlite3 3.40.1 from the quarterly branch:

```sh
cd /tmp
fetch http://pkg.freebsd.org/FreeBSD:13:amd64/quarterly/All/sqlite3-3.40.1,1.pkg
pkg delete sqlite3
pkg install ./sqlite3-3.40.1,1.pkg
pkg install lidarr
```

Or wait a couple of days for the update to hit the pkg mirrors ;P

**Comment by mvanbaak** [comment]
Just to inform: the 3.41.0_1,1 package is available in the /latest upstream pkg repository, no more need to get the version from the quarterly branch

**Comment by mvanbaak** [comment]
Adding some more info: https://cgit.freebsd.org/ports/commit/?id=5fd5f3398b665540ed77893b792e7372f8087f2f
Lidarr has till 2024 to fix the sql to remote the Double Quoted Stringliterals as the FreeBSD sqlite3 port will disable that option by then.
