### ISSUE TITLE
Lidarr seems to alter artist name into artist (clean name) after initial setup?

### ISSUE THREAD

**Issue by wouterverduin** [Lidarr/Lidarr#3503]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I did a fresh install of Lidarr and ran into the following:

1. Add music folder ; Set it to only monitor future releases/
2.  Let it scan.
3. Notice about 20 albums with something missing/incorrect things in the wanted section; Which is odd on its own considering i only want to monitor future albums.
4. After the initial run it seems to start the "rescan folders" task and throwing errors. For example:

MediaFileDeletionService failed while processing [TrackFileDeletedEvent]: Could not find a part of the path '/music/The Offspring (American punk)'.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/music/The Offspring (American punk)'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at NzbDrone.Core.MediaFiles.MediaFileDeletionService.Handle(TrackFileDeletedEvent message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileDeletionService.cs:line 199
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)

This despite having the artist folder name setting as "{Artist Name}"

### Expected Behavior

Scan my database and after initial scan remain the same amount of wanted albums; But actually just the future albums

### Steps To Reproduce

See above

### Environment

```markdown
- OS: Ubuntu 20.04
- Lidarr:1.1.3.2982
- Docker Install: yes (compose)
- Using Reverse Proxy: No
- Browser: Chrome (no UI problem)
- Database: Sqlite 3.40.1
```

### What branch are you running?

Develop

### Trace Logs?

2023-04-06 16:16:39.6|Error|EventAggregator|MediaFileDeletionService failed while processing [TrackFileDeletedEvent]

[v1.1.3.2982] System.IO.DirectoryNotFoundException: Could not find a part of the path '/music/Slipknot (US metal band)'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at NzbDrone.Core.MediaFiles.MediaFileDeletionService.Handle(TrackFileDeletedEvent message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaFileDeletionService.cs:line 199
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)

**Comment by bakerboy448** [comment]
- need the required trace logs the bug report template asks for
- Need the screenshot of the header / path of the artist in lidarr

**Comment by pad92** [comment]
same issue

on lidarr webui : `/music/Library/Merle Haggard and The Strangers`
error log : `[v1.1.4.3027] System.IO.DirectoryNotFoundException: Could not find a part of the path '/music/Library/Merle Haggard and The Strangers'.`

**Comment by DavidHenryThoreau** [comment]
Same issue 
https://github.com/Lidarr/Lidarr/issues/4225 
but albums exists on folder :  
`{Artist_Name}/{Album_Title}/{track:00}_{Track_Title}`

**Comment by DavidHenryThoreau** [comment]
Same issue 
https://github.com/Lidarr/Lidarr/issues/4225 
but albums exist on folder :  
`{Artist_Name}/{Album_Title}/{track:00}_{Track_Title}`

**Comment by bakerboy448** [comment]
Closing as logs have not been provided; can reopen if an when someone provides the required and requested trace logs

**Comment by DavidHenryThoreau** [comment]
After changing `{Artist_Name}` go to `http://LIDARR/artisteditor` and select all and change root folder fix for me :)
