### ISSUE TITLE
Issue updating to latest version

### ISSUE THREAD

**Issue by Minstrel27** [Lidarr/Lidarr#3538]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am running Lidarr in a Truenas jail.   When I tried to update to that latest version (1.1.4.3027) using the internal updater, the process stalls when creating the backup zip file, then gives a "failed" status.   The log has the following information:

2023-04-15 21:04:37.2|Info|InstallUpdateService|Deleting old update files
2023-04-15 21:04:37.2|Info|InstallUpdateService|Downloading update 1.1.4.3027
2023-04-15 21:04:37.9|Info|InstallUpdateService|Verifying update package
2023-04-15 21:04:38.0|Info|InstallUpdateService|Update package verified successfully
2023-04-15 21:04:38.0|Info|InstallUpdateService|Extracting Update package
2023-04-15 21:04:39.2|Info|InstallUpdateService|Update package extracted successfully
2023-04-15 21:04:39.2|Info|BackupService|Starting Backup
2023-04-15 21:06:43.6|Info|InstallUpdateService|Preparing client
2023-04-15 21:06:43.6|Info|InstallUpdateService|Starting update client /tmp/lidarr_update/Lidarr.Update
2023-04-15 21:06:43.6|Info|InstallUpdateService|Lidarr will restart shortly.
2023-04-15 21:06:43.6|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 329
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 312
   at NzbDrone.Common.Processes.ProcessProvider.GetCurrentProcess() in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 52
   at NzbDrone.Core.Update.InstallUpdateService.GetUpdaterArgs(String updateSandboxFolder) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 213
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 166
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 284
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 83
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

I'm not sure if this is a bug or an issue with my setup.

### Expected Behavior

Complete the update

### Steps To Reproduce

Update via internal updater

### Environment

```markdown
- OS: Truenas 13.0-U4
- Lidarr:1.0.2.2592
- Browser: Firefox
- Database:
```

### What branch are you running?

Master

### Trace Logs?

2023-04-15 21:04:37.2|Info|InstallUpdateService|Deleting old update files
2023-04-15 21:04:37.2|Info|InstallUpdateService|Downloading update 1.1.4.3027
2023-04-15 21:04:37.9|Info|InstallUpdateService|Verifying update package
2023-04-15 21:04:38.0|Info|InstallUpdateService|Update package verified successfully
2023-04-15 21:04:38.0|Info|InstallUpdateService|Extracting Update package
2023-04-15 21:04:39.2|Info|InstallUpdateService|Update package extracted successfully
2023-04-15 21:04:39.2|Info|BackupService|Starting Backup
2023-04-15 21:06:43.6|Info|InstallUpdateService|Preparing client
2023-04-15 21:06:43.6|Info|InstallUpdateService|Starting update client /tmp/lidarr_update/Lidarr.Update
2023-04-15 21:06:43.6|Info|InstallUpdateService|Lidarr will restart shortly.
2023-04-15 21:06:43.6|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v1.0.2.2592] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 329
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 312
   at NzbDrone.Common.Processes.ProcessProvider.GetCurrentProcess() in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 52
   at NzbDrone.Core.Update.InstallUpdateService.GetUpdaterArgs(String updateSandboxFolder) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 213
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 166
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 284
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 83
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

**Comment by mvanbaak** [comment]
The in-app updater is not supported on FreeBSD/TrueNAS. It's best to just use pkg to update the package.
