### ISSUE TITLE
[Feature Request]: Limit folder / file name length option.

### ISSUE THREAD

**Issue by gibxxi** [lidarr/Lidarr#356]
Please could the dev team consider adding the option to limit folder (path) / file (name) length. Some albums and/or tracks can have excessively long titles which operating systems then baulk on when trying to interact with them in any way shape or form. Windows is probably the worst culprit for this.

I have used a special naming script in MB-Picard to offset this, but no such option (currently) exists for Lidarr, as far as I can tell. I think the best approach is offering the user the ability to specify all three if nessecary: Artist, Album Folder, and Track Name templates could all do with a path length limit, definable by the user.

TIA.

Gib.

**Comment by gibxxi** [comment]
This is what I currently use:

$if2(%albumartist%,%artist%)/$if(%date%,[$left(%date%,4)] )%album%/$if($gt(%totaldiscs%,1),Disc %discnumber%)/$if($gt(%totaldiscs%,1), %discnumber%-,)$num(%tracknumber%,2) - $left(%artist%,32) - $left(%title%,32)

I've had to limit "artist name" and "track name" to 32 characters, with an extra 4 characters used for disk number (if album is multi-disk only) and track number (2 characters).

The whole library is sync'd from a folder on a hard disk on my PC, via QSync to/from my QNAP NAS. Therefore any changes made (previously by Headphones) were sync'd directly to the local hard disk, acting as a backup.

Also, while i'm on the subject of path length and file name length, I don't know what the dev's plans are for Lidarr, but please, please, please! don't fall into the same trap of only using file names to match tracks. Because with situations like above, where users have to truncate filenames to avoid overly long path lengths, they'll have tracks that Lidarr simply won't detect.

I believe the 'Beets' library can be used to read track tags, this would be a better approach, IMHO. Sonarr, and Radarr don't have any need of metadata/tag scanning as they use nfo's predominantly. For music, while some people do this too, it's extra clutter. Some people (like me) like to keep their artist/album folders clean for sharing / syning with other apps & devices. My music is all tagged with MB-Picard, i'd rather not have to use nfos if it can be avoided.

Gib.

**Comment by Qstick** [comment]
We don't use file names at all to match tracks currently. It's all tags

**Comment by gibxxi** [comment]
Good to know, thanks for the info.

**Comment by bakerboy448** [comment]
https://github.com/Lidarr/Lidarr/issues/1213  would take care of this in theory

**Comment by nandi95** [comment]
example of import failing on: https://musicbrainz.org/release-group/b7493310-d408-44e2-a2d6-bbbd485d7abc

```
[Warn] ImportApprovedTracks: Couldn't import track /data/slskd/downloads/Music to listen to~dance to~blaze to~pray to~feed to~sleep to~talk to~grind to~trip to~breathe to~help to~hurt to~scroll to~roll to~love to~hate to~learn Too~plot to~play to~be to~feel to~breed to~sweat to~dream to~hide to~live to~die to~GO TO (2019)/Bring Me the Horizon - 08 - ±ªþ³§.flac 

[v2.12.0.4634] System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.
   at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in ./Lidarr.Mono/Disk/DiskProvider.cs:line 368
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in ./Lidarr.Common/Disk/DiskProviderBase.cs:line 264
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in ./Lidarr.Common/Disk/DiskTransferService.cs:line 513
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in ./Lidarr.Common/Disk/DiskTransferService.cs:line 299
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.TransferFile(TrackFile trackFile, Artist artist, List`1 tracks, String destinationFilePath, TransferMode mode) in ./Lidarr.Core/MediaFiles/TrackFileMovingService.cs:line 144
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeTrackFile(TrackFile trackFile, LocalTrack localTrack, Boolean copyOnly) in ./Lidarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 79
   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Lidarr.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs:line 240
```
