### ISSUE TITLE
[v0.2.0.371] NzbDrone.Host.Owin.PortInUseException

### ISSUE THREAD

**Issue by engle2192** [lidarr/Lidarr#361]
[Info] Bootstrap: Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.2.0.371
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Lidarr\lidarr.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Lidarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://localhost:9898/*/
[Info] OwinHostController:   http://localhost:9898/
[Info] LidarrBootstrapper: Starting Web Server

[Fatal] ConsoleApp: EPIC FAIL!

[v0.2.0.371] NzbDrone.Host.Owin.PortInUseException: Port 9898 is already in use, please ensure NzbDrone is not already running. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: The parameter is incorrect
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at NzbDrone.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\lidarr\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 52
   --- End of inner exception stack trace ---
   at NzbDrone.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in C:\projects\lidarr\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 63
   at NzbDrone.Host.Owin.OwinHostController.StartServer() in C:\projects\lidarr\src\NzbDrone.Host\Owin\OwinHostController.cs:line 53
   at NzbDrone.Host.NzbDroneServiceFactory.Start() in C:\projects\lidarr\src\NzbDrone.Host\ApplicationServer.cs:line 61
   at NzbDrone.Host.Router.Route(ApplicationModes applicationModes) in C:\projects\lidarr\src\NzbDrone.Host\Router.cs:line 51
   at NzbDrone.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\projects\lidarr\src\NzbDrone.Host\Bootstrap.cs:line 78
   at NzbDrone.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\projects\lidarr\src\NzbDrone.Host\Bootstrap.cs:line 41
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\projects\lidarr\src\NzbDrone.Console\ConsoleApp.cs:line 37

Press enter to exit...

No mater what port I put in the config it will now not start. Tired uninstalling and re-installing. Tried rebooting. Tried leaving default. tried running as a service and not a service. Im on windows 10. Also running sonarr and radarr on same machine. Tried running with others closed also and still not working. any advice?

**Comment by Qstick** [comment]
Have you had any luck?

**Comment by engle2192** [comment]
Actually I did. I just deleted the config file, and db file. Re ran as
admin for first time then closed and open regularly and it was good to go.
This can be closed now.
