### ISSUE TITLE
Lidarr doesn't detect artist folders when the root folder is just a drive letter

### ISSUE THREAD

**Issue by sober-repay** [Lidarr/Lidarr#3840]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding my root folder as E:\, Lidarr doesn't detect any of the artist folders listed. If I manually add an artist, it will locate the folder though within E:\. 

### Expected Behavior

To recognize the artist folders without needing to put them into a subfolder.

### Environment

```markdown
- OS: Windows 10
- Lidarr: Latest
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

2023-07-03 13:46:48.3|Trace|DiskProviderBase|Deleting file: C:\ProgramData\Lidarr\logs\lidarr.txt
2023-07-03 13:46:48.3|Trace|CommandQueueManager|Updating command status
2023-07-03 13:46:48.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-07-03 13:46:48.3|Trace|EventAggregator|Publishing CommandExecutedEvent
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandExecutedEvent -> QualityDefinitionController
2023-07-03 13:46:48.3|Trace|EventAggregator|CommandExecutedEvent <- QualityDefinitionController
2023-07-03 13:46:48.3|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0137356]
2023-07-03 13:46:48.3|Trace|Http|Req: 1184 [GET] /api/v1/command (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:48.3|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:48.3|Trace|CommandQueueManager|Getting all commands
2023-07-03 13:46:48.3|Trace|Http|Res: 1184 [GET] /api/v1/command: 200.OK (2 ms)
2023-07-03 13:46:48.3|Debug|Api|[GET] /api/v1/command: 200.OK (2 ms)
2023-07-03 13:46:48.5|Trace|Http|Req: 1185 [GET] /api/v1/log/file (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:48.5|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:48.5|Trace|Http|Res: 1185 [GET] /api/v1/log/file: 200.OK (1 ms)
2023-07-03 13:46:48.5|Debug|Api|[GET] /api/v1/log/file: 200.OK (1 ms)
2023-07-03 13:46:49.5|Trace|Scheduler|Pending Tasks: 0
2023-07-03 13:46:51.5|Trace|Http|Req: 1186 [POST] /api/v1/command (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:51.5|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Publishing RefreshArtist
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Checking if command is queued or started: RefreshArtist
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Inserting new command: RefreshArtist
2023-07-03 13:46:51.5|Trace|CommandExecutor|RefreshArtistCommand -> RefreshArtistService
2023-07-03 13:46:51.5|Trace|Http|Res: 1186 [POST] /api/v1/command: 201.Created (6 ms)
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Marking command as started: RefreshArtist
2023-07-03 13:46:51.5|Debug|Api|[POST] /api/v1/command: 201.Created (6 ms)
2023-07-03 13:46:51.5|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-07-03 13:46:51.5|Trace|ConfigService|Using default config value for 'rescanafterrefresh' defaultValue:'Always'
2023-07-03 13:46:51.5|Trace|RefreshArtistService|No metadata updated, only scanning new files
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Publishing RescanFolders
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Checking if command is queued or started: RescanFolders
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Inserting new command: RescanFolders
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Updating command status
2023-07-03 13:46:51.5|Trace|CommandExecutor|RescanFoldersCommand -> DiskScanService
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Marking command as started: RescanFolders
2023-07-03 13:46:51.5|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-07-03 13:46:51.5|Trace|EventAggregator|Publishing CommandExecutedEvent
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2023-07-03 13:46:51.5|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Music.Commands.RefreshArtistCommand
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandExecutedEvent -> QualityDefinitionController
2023-07-03 13:46:51.5|Trace|EventAggregator|CommandExecutedEvent <- QualityDefinitionController
2023-07-03 13:46:51.5|Trace|CommandExecutor|RefreshArtistCommand <- RefreshArtistService [00:00:00.0103778]
2023-07-03 13:46:51.5|Trace|Http|Req: 1187 [GET] /api/v1/command (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:51.5|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:51.5|Trace|CommandQueueManager|Getting all commands
2023-07-03 13:46:51.5|Trace|Http|Res: 1187 [GET] /api/v1/command: 200.OK (2 ms)
2023-07-03 13:46:51.5|Debug|Api|[GET] /api/v1/command: 200.OK (2 ms)
2023-07-03 13:46:51.6|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-07-03 13:46:51.6|Info|DiskScanService|Scanning E:\
2023-07-03 13:46:51.6|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-07-03 13:46:51.6|Debug|DiskScanService|Scanning 'E:\' for music files
2023-07-03 13:46:51.6|Trace|CommandQueueManager|Updating command status
2023-07-03 13:46:51.6|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-07-03 13:46:51.6|Trace|EventAggregator|Publishing CommandExecutedEvent
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2023-07-03 13:46:51.6|Trace|TaskManager|Updating last run time for: NzbDrone.Core.MediaFiles.Commands.RescanFoldersCommand
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandExecutedEvent -> QualityDefinitionController
2023-07-03 13:46:51.6|Trace|EventAggregator|CommandExecutedEvent <- QualityDefinitionController
2023-07-03 13:46:51.6|Trace|CommandExecutor|RescanFoldersCommand <- DiskScanService [00:00:00.0571472]
2023-07-03 13:46:51.6|Trace|Http|Req: 1188 [GET] /api/v1/command (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:51.6|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:51.6|Trace|CommandQueueManager|Getting all commands
2023-07-03 13:46:51.6|Trace|Http|Res: 1188 [GET] /api/v1/command: 200.OK (2 ms)
2023-07-03 13:46:51.6|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v1.2.6.3313] System.UnauthorizedAccessException: Access to the path 'E:\System Volume Information' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.Abstractions.DirectoryInfoWrapper.GetFiles(String searchPattern, SearchOption searchOption)
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileInfos(String path, SearchOption searchOption) in ./Lidarr.Common/Disk/DiskProviderBase.cs:line 513
   at NzbDrone.Core.MediaFiles.DiskScanService.GetAudioFiles(String path, Boolean allDirectories) in ./Lidarr.Core/MediaFiles/DiskScanService.cs:line 241
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 artistIds) in ./Lidarr.Core/MediaFiles/DiskScanService.cs:line 131
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in ./Lidarr.Core/MediaFiles/DiskScanService.cs:line 284
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Lidarr.Core/Messaging/Commands/CommandExecutor.cs:line 115
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Lidarr.Core/Messaging/Commands/CommandExecutor.cs:line 42

2023-07-03 13:46:51.6|Debug|Api|[GET] /api/v1/command: 200.OK (2 ms)
2023-07-03 13:46:53.6|Trace|Http|Req: 1189 [GET] /api/v1/health (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:53.6|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:53.6|Trace|Http|Res: 1189 [GET] /api/v1/health: 200.OK (1 ms)
2023-07-03 13:46:53.6|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2023-07-03 13:46:53.6|Trace|Http|Req: 1190 [GET] /api/v1/diskspace (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:53.6|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:53.6|Trace|Http|Req: 1191 [GET] /api/v1/system/status (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:53.6|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:53.6|Trace|Http|Res: 1191 [GET] /api/v1/system/status: 200.OK (2 ms)
2023-07-03 13:46:53.6|Debug|Api|[GET] /api/v1/system/status: 200.OK (2 ms)
2023-07-03 13:46:53.6|Trace|Http|Res: 1190 [GET] /api/v1/diskspace: 200.OK (13 ms)
2023-07-03 13:46:53.6|Debug|Api|[GET] /api/v1/diskspace: 200.OK (13 ms)
2023-07-03 13:46:55.2|Trace|Http|Req: 1192 [GET] /api/v1/log/file (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-03 13:46:55.2|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-03 13:46:55.2|Trace|Http|Res: 1192 [GET] /api/v1/log/file: 200.OK (6 ms)
2023-07-03 13:46:55.2|Debug|Api|[GET] /api/v1/log/file: 200.OK (6 ms)
2023-07-03 13:46:56.6|Trace|Http|Req: 1193 [GET] /logfile/lidarr.trace.txt (from 10.0.0.111 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by sober-repay** [comment]
It shouldn't be as I have Radarr and Sonarr using different drives as root folders without this issue and those drives also contain the 'System Volume Information' folder.

**Comment by sober-repay** [comment]
No. Neither of those two show that error in the trace logs when updating all.

**Comment by sober-repay** [comment]
I changed the permissions on the 'System Volume Information' folder to allow Authenticated Users to read it and that error was cleared. It then returned the same access denied error on the hidden $Recycle.Bin object.

Once I ran a command to delete this, Lidarr then scanned the folder correctly... until I deleted some files, the $Recycle.Bin object returned, and then it failed scanning again.

So, these hidden folders are obviously the issue, and Sonarr and Radarr are obviously coded to ignore them while Lidarr tries stupidly to scan them.
