### ISSUE TITLE
{Artist_Name} but still {Artist Name}

### ISSUE THREAD

**Issue by DavidHenryThoreau** [Lidarr/Lidarr#4225]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I've set {Artist_Name} in `/settings/mediamanagement` but artist is still {Artist Name}

```
2023-10-25 08:25:16.3|Error|EventAggregator|MediaFileDeletionService failed while processing [TrackFileDeletedEvent]

[v1.4.5.3639] System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/media/Musiques/Rodri Opcz'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at NzbDrone.Core.MediaFiles.MediaFileDeletionService.Handle(TrackFileDeletedEvent message) in ./Lidarr.Core/MediaFiles/MediaFileDeletionService.cs:line 198
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
```__

(I've to scroll artist by artist and change directoy manually)

### Expected Behavior

{Artist_Name} can be used

### Steps To Reproduce

Set {Artist_Name} in `/settings/mediamanagement` 

### Environment

```markdown
- OS: Linux
- Lidarr: 1.4.5.3639
- Docker Install: yes 
- Using Reverse Proxy: yes
- Browser: Firefox
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

```
2023-10-25 08:25:16.3|Error|EventAggregator|MediaFileDeletionService failed while processing [TrackFileDeletedEvent]

[v1.4.5.3639] System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/media/Musiques/Rodri Opcz'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at NzbDrone.Core.MediaFiles.MediaFileDeletionService.Handle(TrackFileDeletedEvent message) in ./Lidarr.Core/MediaFiles/MediaFileDeletionService.cs:line 198
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
```__

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by DavidHenryThoreau** [comment]
In `/data/media/Musiques/` all artists are `My_Artist` and i've swtich on lidarr and set `{Artist_Name} `
But I didn't do anything after

**Comment by DavidHenryThoreau** [comment]
I've got :  

`/data/media/Musiques/Rodri_Opcz` but Lidarr thinks the folder is ``/data/media/Musiques/Rodri Opcz` I've set `{Artist_Name}`

**Comment by DavidHenryThoreau** [comment]
Ok, How can I move them all ?
