### ISSUE TITLE
Cannot combine OsPaths

### ISSUE THREAD

**Issue by Chris230291** [Lidarr/Lidarr#4293]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

```
[Warn] DownloadMonitoringService: Unable to retrieve queue and history items from Deluge 
[v1.4.5.3639] System.Exception: Cannot combine OsPaths of different platforms ('/downloads/torrent/incomplete' + 'Artist Name - Song Name\' [2001-Single@320]')
```
I run Lidarr in a Linux Docker container.
It appears to me that Lidarr is treating the commented out `'` as a folder?
I found other people talking about this, but no fixes.

### Expected Behavior

Not sure. Either strip special characters which removes the need for commenting out characters, or understand that its a comment and not a path.

### Environment

```markdown
- OS: Ubuntu Server
- Lidarr: 1.4.5.3639-ls143 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

no need

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Chris230291** [comment]
Yes, it's a literal `\` that causes the issue. There's no more info needed, sorry.

**Comment by alcxander** [comment]
this issue still persists. Looks like somewhere up the chain torrents are getting named with a \ in them to use as an escape character. was mentioned in #248  long time ago. The problem seems pretty serious though like entire platform seems to come to a halt over it and no other file gets added to the system. You can manually go in and remove the torrent then do an interactive search to fine a more suitable torrent but that's not useful if you are looking at 000's files. the literal issue just seems to be torrents have slashes in names that either need to be escaped/sanitised to continue. 

Some other instances of the issue appearing

('/data/torrents' + 'Anthrax Spreading The Disease [320] kbps Beats[TGx]\u2b50')
('/data/torrents' + 'Bastille - Give Me The Future (Deluxe Edition) (2022) Mp3 320kbps [PMEDIA] \u2b50\ufe0f')

would request this is rated as high priority/impact as it seems to break entire system from doing anything afterwards. Can we get something like continue on with other things if this one fails, or remove and try another or just sanitise and continue? Not sure what best approach would be.

**Comment by jtaz16** [comment]
I too am seeing this issue with the \u2b50 which seems to be [C/C++/Java source code/Python source code](https://www.fileformat.info/info/unicode/char/2b50/index.htm) for the yellow star.

`Cannot combine OsPaths of different platforms ('/data/incomplete' + 'Haikyuu!! To the Top 2nd Season - 04 (720p)(Multiple Subtitle)-Erai-raws[TGx] \u2b50')  `

I know I have downloaded some before with a star emote in the name so I wonder why it is all of a sudden poping up for me. Maybe they used different ways to express it that does not include \ / ' ". This seems to happen about once a day for me. In Radarr and Sonarr.

**Comment by brokensolenoid** [comment]
Still seeing this on any torrents with a backslash in the title. It's a real bummer and googling shows me that I'm not alone.. is there any workaround that doesn't involve my intervening constantly?

**Comment by bakerboy448** [comment]
The primary development team is engaged in over five applications, including Lidarr, Prowlarr, Radarr, Readarr, Whisparr, and Sonarr. Currently, there is approximately oneish active developer contributing to these projects, with none of the contributors working on them full-time. Additionally, all members involved, whether in development or support roles, are volunteers and do not receive compensation for their contributions. Each team member balances their commitments alongside full-time jobs, family responsibilities, and other personal obligations.

As a result, the list of tasks to be completed across these projects, along with the various backends and modules, is extensive, while the available time for addressing these tasks is limited.

PRs > complaints about nothing being done

**Comment by davidreverett** [comment]
Is there a process to clear these errors? I see Unable to communicate with Transmission. Cannot combine OsPaths of different platforms ('/mnt/Transmission_Transfer/Completed/Lidarr' + 'Red+Hot+Chili+Peppers+-+Can\'t+Stop+(single)+(320+KBPS)') in my case, the logs say:

2024-12-15 10:13:41.5|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Transmission

[v2.7.1.4417] System.Exception: Cannot combine OsPaths of different platforms ('/mnt/Transmission_Transfer/Completed/Lidarr' + 'Red+Hot+Chili+Peppers+-+Can\'t+Stop+(single)+(320+KBPS)')
   at NzbDrone.Common.Disk.OsPath.op_Addition(OsPath left, OsPath right) in ./Lidarr.Common/Disk/OsPath.cs:line 316
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.GetOutputPath(OsPath outputPath, TransmissionTorrent torrent) in ./Lidarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 242
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.GetItems() in ./Lidarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 71
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in ./Lidarr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 89

Stopping/restarting services doesn't help and the path listed does not exist in Transmission. Need help to clear this error please.

**Comment by brokensolenoid** [comment]
Go to your Activity page and remove the specified download. I just block
the releases now when they have backslashes in file paths.

**Comment by davidreverett** [comment]
Tried doing that and that activity doesn't appear anywhere that I can clear- nothing in Transmission completed activities. It seems to be cached somewhere in Lidarr that I haven't been able to find yet.

**Comment by davidreverett** [comment]
Also still broken in 2.8.2.4493. Tried upgrading- no luck.

**Comment by bakerboy448** [comment]
This issue is open thus it's still an issue.

Contributions welcome.


The primary development team is engaged in over five applications, including Lidarr, Prowlarr, Radarr, Readarr, Whisparr, and Sonarr. Currently, there is approximately one-ish active developer contributing to these projects, with none of the contributors working on them full-time. Additionally, all members involved, whether in development or support roles, are volunteers and do not receive compensation for their contributions. Each team member balances their commitments alongside full-time jobs, family responsibilities, and other personal obligations.

As a result, the list of tasks to be completed across these projects, along with the various backends and modules, is extensive, while the available time for addressing these tasks is limited.

**Comment by davidreverett** [comment]
Well got lucky and figured out how to clear this. I have Transmission/Lidarr using a category folder- named Lidarr. Tried everything up to deleting and renaming this folder to LidarrI since I cannot use the number one in the name. Lo and behold the error cleared- no idea why. 

@brokensolenoid - can you share how you block the releases that have backslashes in file paths? I'd like to set this up given what a PITA this issue is when it happens.

**Comment by marine1988** [comment]
still heapening is very anoying any idea?

**Comment by diegodepablos** [comment]
Yep, still happening:

![Image](https://github.com/user-attachments/assets/c210160d-7e63-4355-800d-521dcbb12e51)

**Comment by brokensolenoid** [comment]
I just made a habit out of opening my download client, searching for "/"
and removing it, then moving on. I made a list of the couple dozen that it
happened with and manually selected sources for them. Given the insane
amount of automation this application afforded, the few hours of manual
intervention was not too much to ask.
