### ISSUE TITLE
[v1.4.5.3639] NzbDrone.Core.ImportLists.Spotify.SpotifyException: [404] Not found.

### ISSUE THREAD

**Issue by icf20** [Lidarr/Lidarr#4352]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

```
[Info] ImportListSyncService: No list items to process 
[Info] ImportListSyncService: Starting Import List Sync 
[Error] FetchAndParseImportListService: Error during Import List Sync of Spotify Playlists (SpotifyPlaylist) 

[v1.4.5.3639] NzbDrone.Core.ImportLists.Spotify.SpotifyException: [404] Not found.
   at NzbDrone.Core.ImportLists.Spotify.SpotifyProxy.Execute[T,TSettings](SpotifyImportListBase`1 list, SpotifyWebAPI api, Func`2 method, Boolean allowReauth) in ./Lidarr.Core/ImportLists/Spotify/SpotifyProxy.cs:line 82
   at NzbDrone.Core.ImportLists.Spotify.SpotifyPlaylist.Fetch(SpotifyWebAPI api, String playlistId) in ./Lidarr.Core/ImportLists/Spotify/SpotifyPlaylist.cs:line 43
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at NzbDrone.Core.ImportLists.Spotify.SpotifyPlaylist.Fetch(SpotifyWebAPI api) in ./Lidarr.Core/ImportLists/Spotify/SpotifyPlaylist.cs:line 34
   at NzbDrone.Core.ImportLists.Spotify.SpotifyImportListBase`1.Fetch() in ./Lidarr.Core/ImportLists/Spotify/SpotifyImportListBase.cs:line 108
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.<>c__DisplayClass4_1.<Fetch>b__1() in ./Lidarr.Core/ImportLists/FetchAndParseImportListService.cs:line 67


[Info] ImportListSyncService: No list items to process 
```

### Expected Behavior

to not fail?

### Steps To Reproduce

import from spotify

### Environment

```markdown
- OS: debian
- Lidarr:1.4.5.3639
- Docker Install: 1.4.5.3639-ls146 by linuxserver.io
```

### What branch are you running?

Master

### Trace Logs?

[Info] ImportListSyncService: No list items to process 
[Info] ImportListSyncService: Starting Import List Sync 
[Error] FetchAndParseImportListService: Error during Import List Sync of Spotify Playlists (SpotifyPlaylist) 

[v1.4.5.3639] NzbDrone.Core.ImportLists.Spotify.SpotifyException: [404] Not found.
   at NzbDrone.Core.ImportLists.Spotify.SpotifyProxy.Execute[T,TSettings](SpotifyImportListBase`1 list, SpotifyWebAPI api, Func`2 method, Boolean allowReauth) in ./Lidarr.Core/ImportLists/Spotify/SpotifyProxy.cs:line 82
   at NzbDrone.Core.ImportLists.Spotify.SpotifyPlaylist.Fetch(SpotifyWebAPI api, String playlistId) in ./Lidarr.Core/ImportLists/Spotify/SpotifyPlaylist.cs:line 43
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at NzbDrone.Core.ImportLists.Spotify.SpotifyPlaylist.Fetch(SpotifyWebAPI api) in ./Lidarr.Core/ImportLists/Spotify/SpotifyPlaylist.cs:line 34
   at NzbDrone.Core.ImportLists.Spotify.SpotifyImportListBase`1.Fetch() in ./Lidarr.Core/ImportLists/Spotify/SpotifyImportListBase.cs:line 108
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.<>c__DisplayClass4_1.<Fetch>b__1() in ./Lidarr.Core/ImportLists/FetchAndParseImportListService.cs:line 67

[Info] ImportListSyncService: No list items to process 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by icf20** [comment]
[lidarr.debug.txt](https://github.com/Lidarr/Lidarr/files/13624911/lidarr.debug.txt)
[lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/13624912/lidarr.trace.txt)
[lidarr.txt](https://github.com/Lidarr/Lidarr/files/13624913/lidarr.txt)

there

**Comment by Eldarock** [comment]
Same error here, and same logs with trace enabled.

**Comment by bakerboy448** [comment]
- closing no trace logs ever provided as required for bug reports
- Backend metadata updates have been occurring, possibly fixed....but not likely a lidarr issue
