### ISSUE TITLE
Couldn't import track. Access to the path is denied.

### ISSUE THREAD

**Issue by mclacore** [lidarr/Lidarr#438]
```
18-7-26 22:32:49.4|Warn|ImportApprovedTracks|Couldn't import track E:\NZBGet\nzb\complete\Paul McCartney-Kisses on the Bottom-CD-2012-8BaLLRiPS INT\07-paul_mccartney-ac-cent-tchu-ate_the_positive.mp3

[v0.3.1.471] System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 232
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 227
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 576
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 320
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 195
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.TransferFile(TrackFile trackFile, Artist artist, List`1 tracks, String destinationFilePath, TransferMode mode) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\TrackFileMovingService.cs:line 127
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.MoveTrackFile(TrackFile trackFile, LocalTrack localTrack) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\TrackFileMovingService.cs:line 86
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeTrackFile(TrackFile trackFile, LocalTrack localTrack, Boolean copyOnly) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 76
   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\TrackImport\ImportApprovedTracks.cs:line 104
```

Seeing this for everything I attempt to download. Setup is identical to Radarr/Sonarr. Obligatory log file uploaded.
[LidarrLog.txt](https://github.com/lidarr/Lidarr/files/2234556/LidarrLog.txt)

**Comment by Qstick** [comment]
Not really sure what would cause this other than security/permission issues. Jump on Discord to see if we can work it out.
