### ISSUE TITLE
Lidarr Root folder change does not update track locations

### ISSUE THREAD

**Issue by ArmofDAO** [Lidarr/Lidarr#4446]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Migrating to new hardware that requires new path mapping.  Old root was /media/music.  New root is /data/media/music.  

When I change the root folder and select 'I'll move the files', the artist path shown on the artist page is changed to /data/media/music, but the track location (as shown by the "I" info button beside the track still shows the root as /media/music.  

If I select an artist and 'refresh and scan' it completes with the error:

`"Artists' root folder (/media/music/) doesn't exist."
`
If I click on the 'rename' module, the target renaming shows a /data/media/music base path, but attempting to complete the rename results in the following error:

```
Failed to rename file /media/music/ARTIST/ALBUM/TRACKNAME.flac: Track file path does not exist

System.IO.FileNotFoundException: Track file path does not exist
File name: '/media/music/ARTIST/ALBUM/TRACKNAME.flac'
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.TransferFile(TrackFile trackFile, Artist artist, List`1 tracks, String destinationFilePath, TransferMode mode) in ./Lidarr.Core/MediaFiles/TrackFileMovingService.cs:line 139
   at NzbDrone.Core.MediaFiles.RenameTrackFileService.RenameFiles(List`1 trackFiles, Artist artist) in ./Lidarr.Core/MediaFiles/RenameTrackFileService.cs:line 122
```

If I delete the /media/music root folder from media management, the next refresh reduces Lidarr's track count to zero and removes all albums from each artist.  

This seems like something simmilar to issue #1088 from 2020.  Though currently the rename function does show what should be the correct path.  

### Expected Behavior

Moving the root folder updates both the artist folder, and the folders of the albums and tracks

### Steps To Reproduce

1. move data from /media/music
2. change root folder to /data/media/music
3. Artist location data field changes, track location data field does not

### Environment

```markdown
- OS: Unraid 6.12.6
- Lidarr:2.1.3.3924-ls56 by linuxserver.io
     - currently on nightly after reading  issue 1088, despite it being from 2020
- Docker Install: lscr.io/linuxserver/lidarr:nightly
- Using Reverse Proxy: no
- Browser: chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs?

[lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/13927440/lidarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by ArmofDAO** [comment]
Additional information:

Once a scan is complete, grouping completes, then it goes to import.  But it references the old /media/music path not the current /data/media/music.  After attempting and failing on the first album the scan/import task errors out and stops

`
|2:47am | CommandExecutor | Error occurred while executing task RescanFolders: File doesn't exist: /media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 01 - Ricky.flac |
...

|2:47am | AudioTag | Tag reading failed for /media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 03 - I Love Rocky Road.flac: Could not find a part of the path '/media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 03 - I Love Rocky Road.flac'. |  
-- | -- | -- | --
  | 2:47am | AudioTag | Tag reading failed for /media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 02 - Gotta Boogie.flac: Could not find a part of the path '/media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 02 - Gotta Boogie.flac'. |  
  | 2:47am | AudioTag | Tag reading failed for /media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 01 - Ricky.flac: Could not find a part of the path '/media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 01 - Ricky.flac'. |  
  | 2:47am | IdentificationService | Identifying album 1/3016 |  
  | 2:47am | TrackGroupingService | Grouping 35267 tracks |  
  | 2:47am | ImportDecisionMaker | Reading file 35267/35267 |  
  | 2:47am | ImportDecisionMaker | Reading file 35266/35267 |  
  | 2:47am | ImportDecisionMaker | Reading file 35265/35267



```
Message
Tag reading failed for /media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 01 - Ricky.flac: Could not find a part of the path '/media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 01 - Ricky.flac'.
Exception
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/music/“Weird Al” Yankovic/“Weird Al” Yankovic (1983)/“Weird Al” Yankovic - - 01 - Ricky.flac'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at TagLib.File.LocalFileAbstraction.get_ReadStream()
   at TagLib.File.set_Mode(AccessMode value)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at NzbDrone.Core.MediaFiles.AudioTag.Read(String path) in ./Lidarr.Core/MediaFiles/AudioTag.cs:line 72
```

**Comment by bakerboy448** [comment]
Logs don't show anything to do with lidarr moving or not moving anything.

**Comment by ArmofDAO** [comment]
Here you go.  Trace logs of the move.  

Steps:
- Restored from backup
- Added new root path (/data/media/music)
- Let settle (Finish scanning folders, updating artists)
- Cleared Logs
- Bulk moved artists (select "I'll move the files")

[lidarr.trace (1).txt](https://github.com/Lidarr/Lidarr/files/13929007/lidarr.trace.1.txt)

- Track information bubble still shows each track path as /media/music
- Rename still tries to name the files with a /data/media/music root, but can not as it is trying to name files in /media/music which dont exist.

**Comment by ArmofDAO** [comment]
I believe I have been able to resolve my issue by creating another faux /media/music directory structure in the same Unraid share, and adding another docker path (/mnt/user/data/temp/media -> /media).  I then moved the music files to this /mnt/user/data/temp/media/music directory.  

Then in Lidarr I changed the root directory of my files from /media/music to /data/media/music.  Lidarr is currently moving the files to the new directory and updating the track level paths.  I will need to manually move many of the unmapped files in my library over, but thats better than having to reconstruct my Lidarr library.  

That being said, this issue should still stay open.  The fix I am employing is a manual one, but Lidarr should be able to update its library location using the bulk move artists feature.

**Comment by Luda83** [comment]
Has this ever been fixed i am in the exact same situation migrating from windows to unraid

**Comment by hugoallaine** [comment]
I'm trying to migrate from docker to kubernetes and I have the same issue

**Comment by crx-au** [comment]
I ended up here as I thought I was experiencing the same issue. In case it is of any benefit to others, I found I could resolve this by adding one last step: manually triggering "Rescan Folders" from "System -> Tasks". As a result, both artist paths and individual track paths have migrated to the new library location.

The only side-effect I've noticed is that the "Unmapped files" list is now showing all of the files in my library that are already correctly mapped to the new path. Not critical for my use case, but worth knowing.
