### ISSUE TITLE
UNIQUE constraint failed: Albums.ForeignAlbumId

### ISSUE THREAD

**Issue by distinguished-git** [lidarr/Lidarr#452]
**Describe the bug**
Unable to load albums for The Moody Blues. Shows 0/0 and fails on refresh.

**To Reproduce**
1. Add artist: The Moody Blues
2. Click refresh albums
3. See error

**Logs**

Message
```
Error occurred while executing task RefreshArtist: constraint failed
UNIQUE constraint failed: Albums.ForeignAlbumId
```

Exception
```
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Albums.ForeignAlbumId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar()
   at Marr.Data.QGen.InsertQueryBuilder`1.Execute() in C:\projects\lidarr\src\Marr.Data\QGen\InsertQueryBuilder.cs:line 138
   at Marr.Data.DataMapper.Insert[T](T entity) in C:\projects\lidarr\src\Marr.Data\DataMapper.cs:line 728
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in C:\projects\lidarr\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 106
   at NzbDrone.Core.Music.AlbumService.AddAlbum(Album newAlbum) in C:\projects\lidarr\src\NzbDrone.Core\Music\AlbumService.cs:line 59
   at NzbDrone.Core.Music.AddAlbumService.AddAlbums(List`1 newAlbums) in C:\projects\lidarr\src\NzbDrone.Core\Music\AddAlbumService.cs:line 62
   at NzbDrone.Core.Music.RefreshArtistService.RefreshArtistInfo(Artist artist, Boolean forceAlbumRefresh) in C:\projects\lidarr\src\NzbDrone.Core\Music\RefreshArtistService.cs:line 132
   at NzbDrone.Core.Music.RefreshArtistService.Execute(RefreshArtistCommand message) in C:\projects\lidarr\src\NzbDrone.Core\Music\RefreshArtistService.cs:line 163
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\lidarr\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 95
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\lidarr\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
```

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
 - Operating System Win10

**Comment by danielunderwood** [comment]
@Qstick could this be due to refreshing after an edit has been made on the musicbrainz side?

**Comment by Qstick** [comment]
Would have to try and reproduce

**Comment by Cypherke** [comment]
Had the same problem with another band. Their latest album was added twice. Once as digital media and one cd. Released on 2 consecutive days. Lucky a delete of the artist and re-add to the database fixed it.
