### ISSUE TITLE
Import spotify playlist imports .... only one  album

### ISSUE THREAD

**Issue by Mrpink200** [Lidarr/Lidarr#4972]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have set a brand new lidarr instance to automaticaly download the new music discussed by the webzine Benzine and published on a spotify playlist  
https://open.spotify.com/playlist/0TbH5Sw2i4GzDqWQ1OstyZ

Despite my serach, trying to modify any option, the list choosen 
<img width="644" alt="Capture d’écran 2024-08-04 à 16 59 17" src="https://github.com/user-attachments/assets/bac6581f-fe13-46c9-9e8c-40d29b6bc492">

lidarr only found and search one artist and album

### Expected Behavior

Grab all the artists and albums found in a playlist

### Steps To Reproduce

1. Add the list "https://open.spotify.com/playlist/0TbH5Sw2i4GzDqWQ1OstyZ" to favorite in spotify
2. In lidarr, choose New Import List
3. Choose Spotify Playlist
4. Connect to spotify account and select "Les Sorties sur BENZINEMAG.NET"
5. Set Monitor to "Specific album" but All album does the same
6. Tick monitor automatically album already in lidarr (or not, do the same)
7. Tick search new elements
8. Save
9. Lidarr finds only one album

### Environment

```markdown
OS: Synology Docker
Version 2.5.1.4285
Version du paquet nightly-a6c6fc1 by hotio
.NET Yes (6.0.32)
Docker Yes
Base de données Sqlite 3.44.2
Migration des bases de données 78
Dossier AppData /config
Répertoire de démarrage /app/bin
Mode Console
```

### What branch are you running?

Nightly

### Trace Logs?

Trace log here : [https://file.io/euLlLzD4njDE](url)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Mrpink200** [comment]
hi; no one else facing the same issue ?

**Comment by SickProdigy** [comment]
I was having an issue before but kind of cleared up now. I had too many playlists on 1 account or something. Maybe the account is rate limited. I was getting 404 for some reason. 

```
2024-11-20 10:53:36.8|Info|ImportListSyncService|Starting Import List Sync
2024-11-20 10:53:38.3|Error|FetchAndParseImportListService|Error during Import List Sync of Spotify Playlists (SpotifyPlaylist)

[v2.7.1.4417] NzbDrone.Core.ImportLists.Spotify.SpotifyException: [404] Resource not found
   at NzbDrone.Core.ImportLists.Spotify.SpotifyProxy.Execute[T,TSettings](SpotifyImportListBase`1 list, SpotifyWebAPI api, Func`2 method, Boolean allowReauth) in ./Lidarr.Core/ImportLists/Spotify/SpotifyProxy.cs:line 82
   at NzbDrone.Core.ImportLists.Spotify.SpotifyPlaylist.Fetch(SpotifyWebAPI api, String playlistId) in ./Lidarr.Core/ImportLists/Spotify/SpotifyPlaylist.cs:line 43
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at NzbDrone.Core.ImportLists.Spotify.SpotifyImportListBase`1.Fetch() in ./Lidarr.Core/ImportLists/Spotify/SpotifyImportListBase.cs:line 114
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.<>c__DisplayClass4_1.<Fetch>b__1() in ./Lidarr.Core/ImportLists/FetchAndParseImportListService.cs:line 82
```

So i created a new account on spotify, restarted shazam, connected it with new account also. Don't touch that playlist for shazam or have issues also... Shazam adding tracks normally, lidarr scanning playlist fine now. So try a different account maybe to fix your issue. 

this error wouldn't go away until i deleted the old playlist/connection. Are you not getting any errors in logs? Just a short form would be nice instead of uploading.
