### ISSUE TITLE
Unable to create directory: 'dir' Could not find file 'dir'

### ISSUE THREAD

**Issue by thehairyvikingniels** [lidarr/Lidarr#549]
**Describe the bug**
 I have recently added a lot (2001 to be exact) of albums from a list to be downloaded. The adding of the albums went fine add were successfully searched for in my torrent sites. They were also succesfully added to qbittorrent.  But when the downloads started to finish they did not get added and tagged in my media library. (I have had it working before with less other albums and artists).
Also the "Check For Finished Download" is taking an average of 30 minutes to complete.

**To Reproduce**
I have not tried to reproduce this error

**Logs**
System->Events gives me two errors over and over again:
-TrackFileMovingService:
Message: 

`Unable to create directory: E:\media\shared media\Muziek\Prince\Around the World in a Day (1985): Could not find file 'E:\media\shared media\Muziek\Prince\Around the World in a Day (1985)'.`

Exeption:
```
System.IO.FileNotFoundException: Could not find file 'E:\media\shared media\Muziek\Prince\Around the World in a Day (1985)'.
File name: 'E:\media\shared media\Muziek\Prince\Around the World in a Day (1985)'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.CreateFolder(String path) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 180
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.CreateFolder(String directoryName) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\TrackFileMovingService.cs:line 214
```
-ImportApprovedTracks:
Message:
`Couldn't import track E:\media\to process\Prince - Around The World In A Day (2013) [24-192 HD FLAC]\04-Raspberry Beret.flac: Could not find a part of the path 'E:\media\shared media\Muziek\Prince\Around the World in a Day (1985)\04 - Raspberry Beret.flac'.`
Exeption:
```System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\media\shared media\Muziek\Prince\Around the World in a Day (1985)\04 - Raspberry Beret.flac'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFileInternal(String source, String destination, Boolean overwrite) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 208
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 203
   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 557
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 297
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in C:\projects\lidarr\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 195
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.TransferFile(TrackFile trackFile, Artist artist, List`1 tracks, String destinationFilePath, TransferMode mode) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\TrackFileMovingService.cs:line 127
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.CopyTrackFile(TrackFile trackFile, LocalTrack localTrack) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\TrackFileMovingService.cs:line 100
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeTrackFile(TrackFile trackFile, LocalTrack localTrack, Boolean copyOnly) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 72
   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\lidarr\src\NzbDrone.Core\MediaFiles\TrackImport\ImportApprovedTracks.cs:line 104```

**System info (please complete the following information):**
 - Lidarr Version: 0.4.0.524
 - Operating System Windows 10 64 bit
 - .net Framework 4.7.2

**Logfiles**
[Lidarr.3.txt](https://github.com/lidarr/Lidarr/files/2616127/Lidarr.3.txt)
[Lidarr.2.txt](https://github.com/lidarr/Lidarr/files/2616128/Lidarr.2.txt)
[Lidarr.4.txt](https://github.com/lidarr/Lidarr/files/2616129/Lidarr.4.txt)
[Lidarr.0.txt](https://github.com/lidarr/Lidarr/files/2616130/Lidarr.0.txt)
[Lidarr.1.txt](https://github.com/lidarr/Lidarr/files/2616131/Lidarr.1.txt)

**Comment by ta264** [comment]
Pretty sure this is a config error.  If you're still having problems try asking on discord, it's easier to debug there
