### ISSUE TITLE
SQLiteException: constraint failed

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#570]
https://sentry.io/lidarr/lidarr/issues/702039354/?referrer=github_plugin

```
SQLiteException: constraint failed
UNIQUE constraint failed: AlbumReleases.ForeignReleaseId
  Module "(unknown)", line 26, in (unknown)
    (unknown)
  File "\NzbDrone.Core\Datastore\Migration\023_add_release_groups_etc.cs", line 242, in WriteReleasesToReleases
    Void WriteReleasesToReleases(System.Collections.Generic.List`1[NzbDrone.Core.Music.AlbumRelease], System.Data.IDbConnection, System.Data.IDbTransaction)
  File "\NzbDrone.Core\Datastore\Migration\023_add_release_groups_etc.cs", line 161, in PopulateReleases
    Void PopulateReleases(System.Data.IDbConnection, System.Data.IDbTransaction)
  File "\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs", line 116, in Process
    Void Process(FluentMigrator.Builders.Execute.PerformDBOperationExpression)
  File "\FluentMigrator\Builders\Execute\ExecuteExpressionRoot.cs", line 67, in ExecuteWith
    Void ExecuteWith(FluentMigrator.IMigrationProcessor)
...
(11 additional frame(s) were not displayed)

System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: AlbumReleases.ForeignReleaseId
  at System.Data.SQLite.SQLite3.Reset (System.Data.SQLite.SQLiteStatement stmt) [0x00083] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) [0x0003c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0016b] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader..ctor(System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery (System.Data.CommandBehavior behavior) [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery () [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at NzbDrone.Core.Datastore.Migration.add_release_groups_etc.WriteReleasesToReleases (System.Collections.Generic.List`1[T] releases, System.Data.IDbConnection conn, System.Data.IDbTransaction tran) [0x000d4] in C:\projects\lidarr\src\NzbDrone.Core\Datastore\Migration\023_add_release_groups_etc.cs:242 
  at NzbDrone.Core.Datastore.Migration.add_release_groups_etc.PopulateReleases (System.Data.IDbConnection conn, System.Data.IDbTransaction tran) [0x00009] in C:\projects\lidarr\src\NzbDrone.Core\Datastore\Migration\023_add_release_groups_etc.cs:161 
  at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process (FluentMigrator.Builders.Execute.PerformDBOperationExpression expression) [0x0002c] in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:116 
  at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith (FluentMigrator.IMigrationProcessor processor) [0x00000] in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator\Builders\Execute\ExecuteExpressionRoot.cs:67 
  at FluentMigrator.Runner.MigrationRunner+<>c__DisplayClass72_0.<ExecuteExpressions>b__1 () [0x00000] in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:489 
  at FluentMigrator.Runner.StopWatch.Time (System.Action action) [0x00006] in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\StopWatch.cs:57 
  at FluentMigrator.Runner.MigrationRunner.AnnounceTime (System.String message, System.Action action) [0x0000c] in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:517 
  at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions (System.Collections.Generic.ICollection`1[T] expressions) [0x00060] in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:489 
```

**Comment by biship** [comment]
0.5.0.585 update broke Lidarr & it won't start.
I don't have a AlbumReleases table in the DB.
I have an Albums table, and none of Albums.Title are blank.

```
18-12-15 01:08:50.4|Info|InstallUpdateService|Downloading update 0.5.0.585
...
18-12-15 01:09:12.3|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Lidarr\lidarr.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-12-15 01:09:12.5|Info|MigrationLogger|*** 23: add_release_groups_etc migrating ***
18-12-15 01:09:12.5|Info|add_release_groups_etc|Starting migration to 23
18-12-15 01:09:13.0|Error|MigrationLogger|System.Data.SQLite.SQLiteException (0x80004005): constraint failed
NOT NULL constraint failed: AlbumReleases.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at NzbDrone.Core.Datastore.Migration.add_release_groups_etc.WriteReleasesToReleases(List`1 releases, IDbConnection conn, IDbTransaction tran) in C:\projects\lidarr\src\NzbDrone.Core\Datastore\Migration\023_add_release_groups_etc.cs:line 242
   at NzbDrone.Core.Datastore.Migration.add_release_groups_etc.PopulateReleases(IDbConnection conn, IDbTransaction tran) in C:\projects\lidarr\src\NzbDrone.Core\Datastore\Migration\023_add_release_groups_etc.cs:line 161
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:line 113
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator\Builders\Execute\ExecuteExpressionRoot.cs:line 67
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489
   at FluentMigrator.Runner.StopWatch.Time(Action action) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\StopWatch.cs:line 57
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489

```

**Comment by ta264** [comment]
This is the big change @Qstick mentioned in discord. Its trying to create an album releases table from the albums table but there's obviously a dodgy entty in Albums

**Comment by ta264** [comment]
@Qstick shall we just wrap the insert in a try catch for now? It means the tracks won't get connected up where there is a dodgy albumrelease entry in albums but it should get sorted by the metadata refresh

**Comment by ta264** [comment]
We could put in a fake title but not sure what we can do about duplicate mbids for albumreleases

**Comment by biship** [comment]
```
select * from Albums where Albums.CurrentRelease NOT like '%title"%';
-- Result: 8 rows returned in 267ms
```
Here's one Albums.CurrentRelease field missing title:

  "id": "249a5c51-7002-309e-9871-95cdcea77153",
  "releaseDate": "2009-05-19T00:00:00Z",
  "trackCount": 20,
  "mediaCount": 1,
  "disambiguation": "",
  "country": [
    "United States"
  ],
  "format": "CD",
  "label": [
    "Aftermath Entertainment"
  ]
}

**Comment by ta264** [comment]
```
\d release_group
                                      Table "musicbrainz.release_group"
    Column     |           Type           | Collation | Nullable |                  Default
---------------+--------------------------+-----------+----------+-------------------------------------------
 id            | integer                  |           | not null | nextval('release_group_id_seq'::regclass)
 gid           | uuid                     |           | not null |
 name          | character varying        |           | not null |
 artist_credit | integer                  |           | not null |
 type          | integer                  |           |          |
 comment       | character varying(255)   |           | not null | ''::character varying
 edits_pending | integer                  |           | not null | 0
 last_updated  | timestamp with time zone |           |          | now()

\d release
                                      Table "musicbrainz.release"
    Column     |           Type           | Collation | Nullable |               Default
---------------+--------------------------+-----------+----------+-------------------------------------
 id            | integer                  |           | not null | nextval('release_id_seq'::regclass)
 gid           | uuid                     |           | not null |
 name          | character varying        |           | not null |
 artist_credit | integer                  |           | not null |
 release_group | integer                  |           | not null |
 status        | integer                  |           |          |
 packaging     | integer                  |           |          |
 language      | integer                  |           |          |
 script        | integer                  |           |          |
 barcode       | character varying(255)   |           |          |
 comment       | character varying(255)   |           | not null | ''::character varying
 edits_pending | integer                  |           | not null | 0
 quality       | smallint                 |           | not null | '-1'::integer
```

So name is `not null` on musicbrainz side, not sure how title has got in empty...

**Comment by ta264** [comment]
If someone with this problem can test the version [here](https://ci.appveyor.com/project/Lidarr/lidarr/builds/21032597/artifacts) that would be really helpful.  Please back up your database first in case it does something undesirable.
